### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by ici-be**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Just a typo in French

### CODE REVIEW

**Comment by AsamK** [comment]
Signal translations are handled on Transifex and exported from there to the git repository.
https://www.transifex.com/signalapp/signal-android/

**Review by vairam-svs — APPROVED** [review]
Yes that is correct:
https://www.google.com/search?q=int%C3%A9r%C3%A9essant does not provide any valid result
But this one does:
https://www.google.com/search?q=int%C3%A9ressant

**Comment by itspiaz** [comment]
Correct.

**Comment by alan-signal** [comment]
Thank you but translations are done only by our community of volunteer translators on a separate service to github. If we merged them here they would only be overwritten.

Please leave feedback on the [community forum](https://community.signalusers.org/c/translation-feedback/27). Our community of volunteer translators are able to view your suggestions, provide feedback on those independent changes, and carry over changes to our translation tools. We appreciate your help.

**Pull request closed without merging**
