### PR TITLE
Fix to a prettySimpleProgressWheel

### LINKED ISSUE #10229: spinning circle for creating the debug log has a square in background
- [X] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
spinning circle for creating the debug log has a square in background

### Steps to reproduce
- generate a debug log
- While waiting for the debug log, see the spinning circle

**Actual result:** spinning circle for creating the debug log has a square in background
**Expected result:** spinning circle for creating the debug log hasn't a square in background
Maybe the spinning circle has blue color, like other spinning circles in Signal

### Screenshots

Screenshot_1606592958 Screenshot_1606592986

### PR DESCRIPTION
**Pull request by Sgn-32**
### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:

 * Virtual device Pixel 2, Android 11.0
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Fix #10229 

The simpleProgressDialog looked like this before:

before light before dark

Now in pretty:

after light after dark

### CODE REVIEW

**Comment by greyson-signal** [comment]
This dialog is actually used in several places, and in those other places we need a background. Having no background ends up working here because it layers nicely with what's underneath it, but that's not always the case. Might be better to have a separate method on SimpleProgressDialog or something, idk.

**Comment by Sgn-32** [comment]
This should be all places where this progress wheel is used. There are other progress wheels like that one for linked devices or another one for/while submitting the debug log (the small one).

Bildschirmfoto_2020-12-07_18-24-15

it's hard to capture screenshots for each case (i'm not fast not enough), but here is the example for the ImageEditorFragment.

signal-2020-12-07-184501 Screenshot_1607362995

Additional it works with ContactSelectListFragment (for creating a group or adding someone to a group), LeaveGroupDialog, PinOptOutDialog and ShareActivity. With the SubmitDebugLogActivity (for creating the debug log) 6 of 8 places are working with a transparent background. I haven't found/saw it for NewConversationActivity and the GroupsV1MigrationInitiationBottomSheetDialogFragment.

The only optional thing is the undimming `dialog.getWindow().setDimAmount(0f);`

**Comment by Sgn-32** [comment]
Added SimpleProgressDialog.show(@NonNull Context context, int background, float dim) with the two parameters for the windows background color and dimming behind the AlertDialog.
Changed the SimpleProgressDialog.show(context) to the new one with the parameters "R.color.transparent" and "0.4f" in the files:

ContactSelectionListFragment
LeaveGroupDialog
SubmitDebugLogActivity
PinOptOutDialog
ImageEditorFragment
ShareActivity

If the dimming is too strong or too weak, the value can be adjusted.

**Comment by Sgn-32** [comment]
Seeing the "ugly" ProgressWheel in the new "set wallpaper" screen.
And how it could look like with a pretty one.

` AlertDialog dialog = SimpleProgressDialog.show(this, R.color.transparent, 0.4f);`

signal-2021-01-22-222720 signal-2021-01-22-224324

**Comment by Sgn-32** [comment]
Added the pretty simple progress wheel on more places.

**Comment by Sgn-32** [comment]
Shouldn't the bot only mark issue as stale and not PRs?
But yes, this PR is relevant and should be merged into the master.

**Comment by alex-signal** [comment]
Bringing this up with design but @greyson-signal has a good point about needing some kind of background.

**Comment by Sgn-32** [comment]
> ... Might be better to have a separate method on SimpleProgressDialog or something, idk.

For this it's a separate method with two parameters for background color (of the small dialog square 120dp x 120dp) and the dim amount. The change from old ProgressWheel to new wheel can be rolled out piece by piece. I use it for 1 year without problems. Maybe the dimAmount (actually 0.4) can be changed to darken the background more.

**Comment by Sgn-32** [comment]
Any response from Design yet? How about a step by step rollout. At the beginning only at SubmitDebugLogActivity?

**Comment by alex-signal** [comment]
Hi! Design is pretty busy right now, but they did mention that they're going to take a look at the progress wheels throughout the app.

**Comment by Sgn-32** [comment]
Design still busy? I have no clue why design would prefer an ugly gray square.

**Pull request closed without merging**
