### PR TITLE
Update Gradle Wrapper from 6.5 to 6.8

### PR DESCRIPTION
**Pull request by EwoutH**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Galaxy S10, Android 10
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Updates the Gradle Wrapper from version 6.5 to 6.8.

As you can see, the `gradle-wrapper.jar` is updated, which speeds up and standardizes downloading the correct Gradle distribution ([reference](https://docs.gradle.org/current/userguide/gradle_wrapper.html)).

Also the `gradlew` and `gradlew.bat` scripts are cleaned up.

> Update Gradle Wrapper from 6.5 to 6.8.
> 
> Read the release notes: https://docs.gradle.org/6.8/release-notes.html
> 
> ---
> 
> The checksums of the Wrapper JAR and the distribution binary have been successfully verified.
> 
> - Gradle release: `6.8`
> - Distribution (-all) zip checksum: `a7ca23b3ccf265680f2bfd35f1f00b1424f4466292c7337c85d46c9641b3f053`
> - Wrapper JAR Checksum: `e996d452d2645e70c01c11143ca2d3742734a28da2bf61f25c82bdc288c9e637`
> 
> You can find the reference checksum values at https://gradle.org/release-checksums/
> 
> ---
> 
> 🤖 This PR has been created by the [Update Gradle Wrapper](https://github.com/gradle-update/update-gradle-wrapper-action) action.

### CODE REVIEW

**Comment by EwoutH** [comment]
I will test this PR further after #10588 is merged, since that contains standardized APK builds and tests PRs more extensively.

**Comment by EwoutH** [comment]
Tested and ready for review.

**Comment by EwoutH** [comment]
Rebased and signed commit.

**Comment by alan-signal** [comment]
It's as much effort to bring in the PR as it is to run `./gradlew wrapper --gradle-version 6.8`

So we will do this update ourselves when we need to, thank you.

**Comment by EwoutH** [comment]
To give some context (should have done that probably earlier), this was a setup to start working on some Gradle warnings (in which case it's nice to have the latest warnings and depreciation notices), when do you expect to update the Gradle wrapper?

The end goal would be to build successfully with failure on warnings (`--warning-mode=fail` [in Gradle](https://docs.gradle.org/current/userguide/command_line_interface.html#sec:command_line_warnings)).

**Comment by alan-signal** [comment]
I don't know when we would update. Are there actually more or different warnings with 6.8 vs 6.5?

**Comment by EwoutH** [comment]
I compared the logs between Gradle 6.5 and 6.8.1, and currently both give the same warnings.

- [signal-gradle-6.5-log-stripped.txt](https://github.com/signalapp/Signal-Android/files/5860397/signal-gradle-6.5-log-stripped.txt)
- [signal-gradle-6.8.1-log-stripped.txt](https://github.com/signalapp/Signal-Android/files/5860398/signal-gradle-6.8.1-log-stripped.txt)

There are methods in the API that [got depreciated](https://docs.gradle.org/6.8.1/userguide/upgrading_version_6.html) since Gradle 6.5 however. Some of those will be removed in Gradle 7, so using a recent Gradle version helps to give an as early warning as possible.

It also helps with performance in some cases (I noticed about a 10 second speedup between 6.5 and 6.8.1).

I think a great workflow would be:

- Having a CI check once a week if a new Gradle version is available, and open the PR if so
- Have full CI run on that PR, with `--warning-mode=fail` enabled to report all warnings and fail if there are more than 0
- Resolve all the warnings. There's no hurry to do this because Gradle warns far ahead, and since Gradle is regularly updated there won't be a large amount of warnings each time
- When all the warnings are resolved the CI should pass and the new Gradle version can be merged

Of course that will require some effort to get `--warning-mode=fail` passing initially, but once all existing warnings are gone it will be a small effort each time.

**Pull request closed without merging**
