### PR TITLE
Pull Request 

### PR DESCRIPTION
**Pull request by SushantDhiman2004**
### First time contributor checklist

- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [X] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by alan-signal** [comment]
@SushantDhiman2004 @DanielNovak @nrizzio 

I am not sure what this is PR about, the current state of this PR looks like a git user error, hundreds of commits by other people, there's no description or title. That's not unusual yet people are discussing quite important things on here.

Please move discussion to issues or the community forum  https://community.signalusers.org/

**Comment by u32i64** [comment]
> That's not unusual yet people are discussing quite important things on here.

@alan-signal This indeed appears to be a user error, but just to clarify regarding the comments: it looks like GitHub simply grabbed all comments from the PR's commits and displayed them in this PR (notice that, unlike your comment `alan-signal commented <relative time>`, they say `<username> commented on [<file> in] <commit id> <relative time>`).

**Comment by DanielNovak** [comment]
Yes, this is some weird GitHub issue. It's just grabbed my comment from the master - I just put a comment directly on a file in the master. Not in this PR. :-(

**Comment by alan-signal** [comment]
@DanielNovak ah OK thanks!

**Pull request closed without merging**
