### PR TITLE
present perfect for some English strings

### PR DESCRIPTION
**Pull request by lpirl**
What would you think of some more present perfect for some English strings where the focus is on the current situation, rather than the past? Simple past triggered me especially in "message was deleted" because I suppose Signal is actually trying to tell users that the message *is deleted*.

Feel free to add comments in the review where my changes are inappropriate.

If this PR is welcome, I'd port it to iOS and desktop.

### CODE REVIEW

**Comment by lpirl** [comment]
I am happy to apply some changes, if desired. :)

**Comment by alex-signal** [comment]
Hi! I'll bring this up with our localisation manager.

**Comment by lpirl** [comment]
That is great, thank you @alexr-signal .

**Comment by lpirl** [comment]
still waiting for response from localisation manager, happy if this would not be closed

**Comment by greyson-signal** [comment]
Hi, I think we'll be keeping the strings as they are, but thank you!

**Comment by lpirl** [comment]
Sad, because IMHO, present perfect would be more correct in some cases.
Anyway, thanks a lot for considering.

**Pull request closed without merging**
