### PR TITLE
Fixes #8512

### LINKED ISSUE #8512: Static font size for quoted messaged (no adaptation to the font size setting)
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Adapting the font size in the settings does not effect quoted messages. When quoting a message, the font size of the quoted message always remains the same (see screenshots).

### Steps to reproduce
- set the "message font size" to anything other than "Normal" in "Chats and media" -> "Chats" -> "Message font size".
- Quote a message.

**Actual result:** The font size of the quoted messages is "Normal"
**Expected result:** The font size of the quoted messages should adapt to the chosen option in the settings.

### Screenshots
Font size setting:
settings

Correct font size when font size is set to "Normal":
font-size-normal
Font size does not adapt when font size is set to "Small":
font-size-small
Font size does not adapt when font size is set to "Extra large":
font-size-large

### Device info

**Device:** Fairphone 2
**Android version:** 7.1.2
**Signal version:** 4.31.6

### Link to debug log
n/a

### PR DESCRIPTION
**Pull request by jakubgregorek**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual device Pixel 2, Android 9.0
 * Virtual device Galaxy Nexus, Android 4.4
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Fixes #8512.

Quoted messages use the font size from the chat settings.

### CODE REVIEW

**Comment by jahed** [comment]
Hi, @ianmcderp. Is there anything blocking this? It's been a while since it was submitted.

**Comment by ianmcderp** [comment]
@jahed well, by now it seems that a conflict needs to be resolved prior to merging the change back to origin/master. @jakubgregorek any chance you could fix the occured conflicts in your branch?

**Comment by jakubgregorek** [comment]
@ianmcderp it should be done now.

**Comment by jakubgregorek** [comment]
Is there something preventing this pull request from being merged? :-)

**Comment by Duskfen** [comment]
Would be nice if this issue would be fixed (this pull request merged) since it reduces the user experience

**Comment by Otiel** [comment]
The issue is fixed, this pull request can be closed.

**Pull request closed without merging**
