### PR TITLE
Allow users to fall back to pins or patterns when biometric auth cannot be used to unlock Signal

### LINKED ISSUE #9407: Can't unlock Signal with the screen lock PIN when a fingerprint is set up
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

### Bug description

Fingerprint unlock is handy, but sometimes it just doesn't work, for example when wearing gloves, or if your fingerprint has scratches or marks. Android is smart and it always allows you to unlock the screen with the screen lock PIN (or password) if desired. This isn't the case with Signal: if fingerprint unlock is configured, there is no way to unlock Signal with the screen lock PIN. 

### Steps to reproduce

- Setup everything to unlock Signal with the screen lock fingerprint
- Lock the screen
- Pretend you can't use your fingerprint to unlock
- Happily unlock the phone with the PIN
- See how you can't unlock Signal in any way.

**Expected result:** a PIN unlock option is available.

### Device info

**Device:** Xiaomi Mi A2
**Android version:** 10
**Signal version:** 4.55.8

### PR DESCRIPTION
**Pull request by fumiakiy**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Essential PH-1 Android 10
 * AVD API 30
 * AVD API 29
 * AVD API 28
 * AVD API 23
 * AVD API 21
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------
Use the new BiometricPrompt to allow users to fall back to pins or patterns when fingerprints or other biometric authentications may not be convenient. Fixes #9407

### CODE REVIEW

**Comment by Genis-Sage** [comment]
hey @fumiakiy 
perhaps your pull request would also solve #10166 

with your pull request, what happens, when you make too many wrong tries?
will it automatically jump to pin entry?

**Comment by fumiakiy** [comment]
Hi @Genis-Sage ,

I just tested on emulators (api 29 and api 30) and yes, this implementation of using BiometricPrompt automatically jumps to the fallback lock method such as pin or pattern when the fingerprint fails too many times.

**Comment by Leptopoda** [comment]
hi @fumiakiy 
what is the difference to the recently implemented https://github.com/signalapp/Signal-Android/commit/3c4252a933a800f5f6dd8ec61bda4ec113350903?

**Comment by cody-signal** [comment]
Merged as 3c4252a933a800f5f6dd8ec61bda4ec113350903

**Pull request closed without merging**
