### PR TITLE
Use OsmDroid and OpenStreetMap when Google Play Services is not available

### LINKED ISSUE #7835: Position sharing without Gservices
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On a phone that doesn't have Google Services, I can't share my location. When I press the "Position" button the flap goes down without an error message.

### Steps to reproduce
- Open any conversation
- Try to share your position
- You can't !

**Actual result:** The application does not generate a message
**Expected result:** The application should generate a message with a Google Maps showing my location.

### Screenshots
No screenshots because no error message appears.

### Device info
**Device:** Xiaomi Mi Note 2
**Android version:** 8.1.0
**Signal version:** 4.20.4

### Link to debug log
https://cloud.hugoleroux.ovh/index.php/s/jrRYNrzFRjBmgD9

### PR DESCRIPTION
**Pull request by hfjooste**
Fixes #7835 

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Physical device: Samsung Galaxy S7 Edge (Android 7.0)
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
I've added OsmDroid to load/display the map and allow a user to select a location. The user can also specify an optional location name and address. This is only used when the Google Play Services is not installed (or disabled). I've also replaced the Google Maps link with OpenStreetMap when the Google Play Services is not available

### CODE REVIEW

**Comment by Diapolo** [comment]
Great addition, the less Google Signal uses, the better it gets :-). Thank you!

**Comment by moxie0** [comment]
Thanks @hfjooste, what we really want is a library that provides OSM which is API compatible with MapView and PlacePicker. This PR is quite large and introduces a new activity that would require design to become compatible with PlacePicker. 

Can you instead package this code into a library which provides API-compatible OSM implementations of MapView and PlacePicker? That way you can maintain it long term, design can be done independently of Signal, it would be easy for us to drop in (same code in our application for play services enabled and disabled devices), and the library would benefit other projects which want the same.

**Comment by theel0ja** [comment]
@moxie0 microG has some.

https://github.com/microg/android_packages_apps_GmsCore

**Comment by ronidee** [comment]
> 
> 
> Thanks @hfjooste, what we really want is a library that provides OSM which is API compatible with MapView and PlacePicker. This PR is quite large and introduces a new activity that would require design to become compatible with PlacePicker.
> 
> Can you instead package this code into a library which provides API-compatible OSM implementations of MapView and PlacePicker? That way you can maintain it long term, design can be done independently of Signal, it would be easy for us to drop in (same code in our application for play services enabled and disabled devices), and the library would benefit other projects which want the same.

@moxie0 What's the state of this? Are you still using PlacePicker and MapView and would a lib which need to be also API compatible with MapView or is the PlacePicker a wrapper of MapView?
I don't know if you're active in the forum but if so, [here is a thread](https://community.signalusers.org/t/want-to-contribute-in-signal-android/16463) with some people (at least one: me) who want do finally do this.

**Pull request closed without merging**
