### PR TITLE
Added apk download from signals website and updated copyright year to 2021

### PR DESCRIPTION
**Pull request by Goldmaster**
### First time contributor checklist

- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [X] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by Goldmaster** [comment]
wonder if its better to say to present for the copyright year?

**Comment by alex-signal** [comment]
Thank you!

This will go out in `5.22`

**Comment by Goldmaster** [comment]
Any reason why, you have not added the apk download link into the read me? Not everyone wants to use play store. Seams a bit counter initiative Considering signal is about privacy?

**Comment by Goldmaster** [comment]
@alex-signal Any reason why, you have not added the apk download link into the read me? Not everyone wants to use play store. Seams a bit counter initiative Considering signal is about privacy?

**Comment by alex-signal** [comment]
@Goldmaster This was added a while back, we just changed the hyperlink text to read `signal.org`.

https://github.com/signalapp/Signal-Android/commit/dbcc5d696d6a99ed9b081ed72b50d70e2911dcd7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by Goldmaster** [comment]
@alex-signal ah ok, I thought it was from the website. Allot of websites would say in apk format so that users know the app is available to sideload. But thats fine anyhow.

**Pull request closed without merging**
