### PR TITLE
fix: fixed fragment permission request method

### PR DESCRIPTION
**Pull request by mridulbarman027**
### First time contributor checklist

- [ x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x ] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ x] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [ x] My contribution is fully baked and ready to be merged as is
- [ x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by clark-signal** [comment]
Hi thanks for the PR! But it's not clear what this is fixing.

**Comment by mridulbarman027** [comment]
Hi @clark-signal, here its calling same function twice which is very inefficient for user's device. So I have converted two functions into one and assigned them into one variable and used that variable in two places.

**Comment by greyson-signal** [comment]
Thanks! If you sign the CLA, we'll include the PR in 6.32.

**Comment by mridulbarman027** [comment]
I signed

**Comment by greyson-signal** [comment]
This will be in 6.42, thanks!

**Pull request closed without merging**
