### PR TITLE
Improve registration exception handling

### LINKED ISSUE #7819: App doesn't report 413 errors correctly
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I've been fighting with restoring Signal from a Titanium Backup.  There's a number of open and closed issues on that subject, but this is a side issue that has caused me to waste several hours flailing at getting my phone registered _at all_, much less with my data.

I discovered via signal-cli that I was getting rate limited (413) errors, presumably from attempting to re-register the same device several times.  However, the app does not report this error, it just says "Unable to connect to service."

### Steps to reproduce
- uninstall the app
- reinstall the app (from backup or fresh or an older apk (4.15.5 is the last known good for being able to import backed-up data...)
- attempt to register the device
- repeat first three steps multiple times.  Eventually you'll get rate limited.  It doesn't require a flood, just a half-dozen attempts in an hour.
- See a very unhelpful error.

**Actual result:** A toast pops up with "Unable to connect to service." etc, etc.
**Expected result:** A toast pops up with something useful to say, like "You've attempted to register this number too many times, please wait an hour to try again."

### Device info

**Device:** Oneplus X
**Android version:** Lineage 14.1
**Signal version:** 4.19.3 and 4.15.5.

### PR DESCRIPTION
**Pull request by cascheberg**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on this device:
 * Virtual device, Android 7.1.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Handle rate limit exception during registration process. Handling of other exceptions can be added easily.

Fixes #7819, which is labeled as help wanted.

registrationexception

### CODE REVIEW

**Comment by cascheberg** [comment]
PR rebased tested again

**Comment by aaronjanse** [comment]
Could this please be merged? I think a friend of mine just ran into the a scenario where this PR would be helpful

**Comment by cascheberg** [comment]
Implemented in 2915e4698c9e18ec980369b0450c8f838a6d8264

**Comment by ScottInMaricopa** [comment]
I've noted that when you get the message that you have attempted to register too many times, the system usually "resets" and lets you try after an hour or so.
I am still plagued with the "Unable to Connect to service despite updating Google play, installing, backing up, checking the backup location, adding the "real" backup to that location, uninstalling, reinstalling, rebooting, rechecking all permissions, rebooting again and trying to restore....   If you get all that then you know where I have been.......  Uggggggg

Stinks.  Note...   Signal restored fine to my new Moto G7 Power but I will not install on my wife new Moto G7 Power.

Scott in Arizona --- if anyone can please help.

**Pull request closed without merging**
