### PR TITLE
Run Espresso tests on pull requests

### PR DESCRIPTION
**Pull request by hannesa2**
The headline says everything

### CODE REVIEW

**Comment by alan-signal** [comment]
Why changed over to mac? That has cost implications.

**Comment by hannesa2** [comment]
only there you have x86 acceleration

**Comment by alan-signal** [comment]
> only there you have x86 acceleration

What is the difference in speed?

**Comment by hannesa2** [comment]
> That has cost implications.

If you think it has some, you should close it

**Comment by hannesa2** [comment]
> What is the difference in speed?

You ask about speed comparing between `arm` and `x86` with hardware acceleration ?

Btw, you can test if this is necessary, or the action already has it

**Comment by alan-signal** [comment]
FYI macos instance costs 10x linux!

You can put the `runs-on` back to linux and we will just see how long the actions take to execute.

**Comment by hannesa2** [comment]
> FYI macos instance costs 10x linux!

Please show me the source of this info

**Pull request closed without merging**
