### PR TITLE
Fix a bug that forward/reply buttons appear in reverse in RTL layout

### LINKED ISSUE #11006: [RTL] ActionBar Mirroring issue
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Forward and Reply ActionBar buttons aren't correctly mirrored.

### Steps to reproduce
- Use RTL

### Screenshots

image

### Device info

**Device:** HTC M9
**Android version:** 7.0 or higher
**Signal version:** 5.3.12

### PR DESCRIPTION
**Pull request by fumiakiy**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * AVD Pixel 3a API 30
 * AVD Pixel 3a API 29
 * AVD Nexus 6P API 27
 * AVD Pixel API 23
 * AVD Nexus 5X API 21
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Due to [a known Android bug](https://issuetracker.google.com/issues/37138973), `autoMirrored` attribute in a vector drawable doesn't work if it's used as an icon of a menu item. It is confusing for RTL language users because it appears the exact opposite of what they actually do.

To work around the bug, the PR moves around the xml files so that the icon for `forward` is used for `reply` in RTL and the icon for `reply` is used for `forward` in RTL.

Fixes #11006.

### Screenshots
|API|Before|After|
|---|---|---|
|21|It was working all right until Android 7.1.<BR>The *after* screenshot here is to show <BR>there is not a regression after the PR.|Screenshot_1613861520|
|21|It was working all right until Android 7.1. <BR>The *after* screenshot here is to show <BR>there is not a regression after the PR.|Screenshot_1613861551|
|29|Screenshot_1613861889|Screenshot_1613861702|
|29|Screenshot_1613861878|Screenshot_1613861716|

### CODE REVIEW

**Comment by alan-signal** [comment]
This has changed the arrow direction when you drag a message to reply.

image

Should be:

image

Make sure when you're changing the appearance of an icon you search for all usages.

**Comment by fumiakiy** [comment]
I see it happening when you change the system language to RTL and then LTR again at least in my API 23 emulator. If you switch language in Signal settings it works fine for me. Let me know if you have other ways to reproduce the bug.

I'll convert the PR to draft for now.

**Comment by fumiakiy** [comment]
> This has changed the arrow direction when you drag a message to reply.

The issue was due to ViewCache was not purged on configuration change event when what was changed was the layout direction. Fixed in [884ff36]. Please note that this fix was also in the other RTL related PR too because it was also required there. I cherry picked the commit in order for this PR to be self contained.

> If menus are the place with the problem, maybe a new menu xml for RTL is the solution?

Yes, it is one way to fix this issue, to add `menu-ldrtr` and `menu-ldltr-night` directories and use reversed `icon` in the file in the directories. I didn't go that path because this is an Android(X) bug and They seem to be willing to fix it in the near future. When it was fixed in an androidx release however, the problematic `autoMirrored` attribute would suddenly start to work correctly. And that means the _reversed_ settings of the icon will appear _reversed_-_reversed_, meaning the original issue appear to be resurrected.

The changes I am suggesting in this PR is to not rely on the `autoMirrored` attribute in vector drawables that are used in menus, so that the future bug fix wouldn't affect the state of the app.

**Comment by greyson-signal** [comment]
Thanks! This will go out in the next release :)

**Pull request closed without merging**
