### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] - NA - I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Friendly ping? @moxie-signal?

**Comment by greyson-signal** [comment]
Hi there, we'll look into putting this into the 4.56 release. Thanks!

**Comment by alan-signal** [comment]
We'll probably go with a new `- uses` in existing build action.

Can you explain why `pull_request` was important and how someone can get around the system if that's not there?

**Comment by alan-signal** [comment]
I presume this does not cover gradlew and gradlew.bat scripts, but they sometimes update at the same time as the jar don't they?

**Comment by JLLeitschuh** [comment]
@alan-signal This is purely to check the binary files that are not human readable/reviewable.

**Comment by alan-signal** [comment]
Well you should consider that as I don't know what their content should be, so cannot review even if I can read them, and in my experience its a step people miss causing the scripts to be out of step with the binary.

Bottom line, even with this check in place, if we still have to do the update ourselves to ensure the scripts are correct then that seems to be against the goal of your project, i.e. trusting gradle wrapper update PRs from an open source community.

**Comment by JLLeitschuh** [comment]
> Bottom line, even with this check in place, if we still have to do the update ourselves to ensure the scripts are correct then that seems to be against the goal of your project, i.e. trusting gradle wrapper update PRs from an open source community.

Given your security model, I think this is totally reasonable.

**Comment by JLLeitschuh** [comment]
Aside: I also want to make your team aware of this post:
https://community.signalusers.org/t/utilize-new-gradle-dependency-verification-feature/11596

**Comment by alan-signal** [comment]
If you want change this PR over to add the single line to `https://github.com/signalapp/Signal-Android/blob/master/.github/workflows/android.yml` then I can pull in and give you the contributor credit.

**Comment by JLLeitschuh** [comment]
Sounds good, I'll do it tomorrow.

**Comment by JLLeitschuh** [comment]
Updated!

**Comment by alan-signal** [comment]
Merged in 455974cb05296357fe51f86b8091db455f1a4c80

Thank you!

**Pull request closed without merging**
