### PR TITLE
Hide megaphones and floating buttons when opening search

### PR DESCRIPTION
**Pull request by clauz9**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nokia 3.1, Android 10
 * Huawei L29, Android 8
 * Samsung A10, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Currently the megaphones, and the floating buttons aren't hidden when search is opened, which means they take up screen space. So I made them fade in and out.

<details>
<summary>Screenshot before</summary> 

image

</details>

<details>
<summary>Screenshot after</summary>

image

</details>

### CODE REVIEW

**Comment by clauz9** [comment]
it turns out, the PIN reminder megaphone, and I assume any megaphone will show up again onResume(), this also affects multi select UI 

<details>
 <summary>Screenshot</summary>

image

</details>

Turning this into a draft for now... 🤔

**Comment by clauz9** [comment]
Turns out the flicker of the floating buttons, was caused by my custom keyboard, the flicker doesn't happen with the Google keyboard, or on my other 2 devices 🤔 

So I'm reverting the last commit

**Comment by alex-signal** [comment]
Thanks! I'll bring this in for review.

**Comment by cody-signal** [comment]
Wasn't this merged in already?

**Pull request closed without merging**
