### PR TITLE
Fixes #8692 (workaround!) Detect missed Notifications + shows warning to user

### LINKED ISSUE #8692: Messages sometimes show up late and/or in bunches
- [x ] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Typing on the desktop client and after awhile I heard my phone buzz. Opened it up and a flood of signal messages come in that were from the last several minutes (15 minutes maybe) 

### Steps to reproduce
- use desktop client, message friends on signal.
- sometimes hear phone buzz
- pick up phone and turn on screen

**Actual result:** signal messages from recent history flood in 
**Expected result:** messages come into phone roughly at the same flow as desktop while on the same network

### Device info
**Device:** Samsung galaxy s9
**Android version:** 9.0 stock Verizon
**Signal version:** 4.35.3

### Link to debug log
https://debuglogs.org/6d156ab53db2297c534498e59937440ab48bb8d5ef77527afd850adcaa89c26f

### PR DESCRIPTION
**Pull request by rainerm77**
Related issues #9438 #10168 (maybe more)

### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Moto G5 Android 8.1.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Workaround for issue #8692 (and related issues #9438 #10168 and maybe more):

- What:
Unless we can really finally solve this issue, better show an explanation why on some phones Notifications are not working correctly when Signal is in background.

- How:
After 3x times a notification was shown >1 hour delayed (although notifications were activated!), then display a warning/info to the user (using "megaphone")

- Known limitation:
It only can detect *potentially* missed Notifications, thus false positives are possible. It might shows the warning to users who maybe intentionally put their phone offline for long periods (over night, during a flight etc).
For this reason I limited the "megaphone" to appear a maximum of 7 days...

Background: The workaround cannot distinguish if Signal was forced to sleep by Android, or if user intentionally went offline. (Maybe a potential solution to overcome this limitation would be: Maybe checking logcat -> ConnectivityService -> to check if "DISCONNECT / CONNECT" happened since Signal was in foreground the last time before)

- Further details and user experiences described at SignalCommunity:
https://community.signalusers.org/t/severe-notification-issue-please-implement-suggested-workarounds/37732

- ! Important remark for merging!:
After testing, before final merging, please edit following line (increase timeout from 1min to 1hour):
app/src/main/java/org/thoughtcrime/securesms/messages/MessageContentProcessor.java
"if(msgReceptionDelaySec >= 60*1000) { // TODO: Change from 60 to 3600 before release! 60 is used for test purposes"

### CODE REVIEW

**Comment by rainerm77** [comment]
Hello @greyson-signal
I've observed that you have been previously involved and informed about the old issue #8692, therefore I hope you will be interested in my suggested "workaround-solution".

Remark: As recently discussed in the SignalCommunity (see link above), many users agree with me and would also favor at least such a workaround-solution of currently having nothing and leaving unexperienced users clueless (or frustrated) why it Notifications don't work some phones...

Thanks in advance, BR,
Rainer

**Comment by rainerm77** [comment]
Hello @cody-signal 

Since you have recently worked on "Notification"-related features for 5.28, could you maybe also consider/discuss this notification-related PR in your team?
Or maybe you could take this PR as inspiration, and come up with a related, but maybe better idea...?

The last few months, once again had a few "newcomer-to-Signal" friends, which I've tried to convince to switch to Signal. However, they also got frustrated after a few days about issue not getting notifications on their smartphones. Although it surely was because of energy-saving settings, they didn't know about that, and after 1-2 weeks they deleted Signal again :-(

--> Exactly to inform such "normal people" (none-tech-experts) about a probable Android setting as root-cause, my PR is intended to help. These people just don't know that such settings even exist (since it works for WhAp they usually never need to care about such settings) - that's the real issue here.

Thanks, best regards,
Rainer

**Comment by greyson-signal** [comment]
I don't disagree with the idea behind this, but I do think it's going to require more thought. The biggest problem would be false positives triggered by people being offline.

**Comment by rainerm77** [comment]
@greyson-signal wrote:
> The biggest problem would be false positives triggered by people being offline.

Ok, you are right, I've also thought about that quite a while, because I agree that this would be the remaining negative side-effect. At least in this PR, I've already implemented two suggested countermeasure for that:
- to limit the whole warning mechanism to only 7 days, so that it is only intended for "newcomers to Signal" for 1 week:
see Megaphones.java:
"shouldshowMissedBackgroundNotificationsMegaphone(context) ? ShowForDurationSchedule.showForDays(7)"
- and show the notification only after 3 new occurrences
see Megaphones.java:
private static boolean shouldshowMissedBackgroundNotificationsMegaphone(@NonNull Context context) {
    // Suggestion to better wait for 3 times "potential-missed-notifications" were counted until raising the megaphone (to avoid annoying users too often?)
    return SignalStore.misc().getNrOfPotentiallyMissedNotifications() >= 3;
}

However, I'm aware that this is still no perfect solution. On the other hand, this PR is anyway just meant as an intermediate-solution (maybe for 1 year?) until Google would hopefully improve the root-cause for this whole "missed-notification issue due to energy-saving-settings" in the future.
At least for now, the best solution _would require additional code for auto-detecting how many hours the phone has been offline_ between last time Signal-App has been used. --> My hope would be that someone of your team (real android-professionals!!) would know a better solution and could enhance my idea accordingly.

When I've worked on this PR I've thought about this remaining issue, and googled many hours if I find an elegant way (=with little overhead) using bulit-in Android-APIs, to query, if and how long the phone has been offline. Unfortunately, I only came up with the idea parsing some sys-logfiles for that purpose, but this would be too much overhead I assume.

Alternative:
I hope you could discuss in your team, if someone would know a better or elegant solution for that. Or otherwise - maybe you could discuss in your team how to convince Google to implement a "real perfect solution" in the next year: Somehow defining on Android-System-level some generic kind of "messenger-application classification", which all vendors observe, so that eventually all messenger-apps in the future are allowed to run in background per default.

Thanks, best regards,
Rainer

**Comment by rainerm77** [comment]
@greyson-signal wrote:
> I don't disagree with the idea behind this, but I do think it's going to require more thought. The biggest problem would be false positives triggered by people being offline.

Hello @greyson-signal Since this PR might be automatically closed: Do you see any chance for further discussing in your team, if you could somehow take my suggested idea (auto-detecting missed notifications) as input, and maybe could improve it to better avoid false-positives?
Sorry, I don't have so much Signal programming experience & skills to implement a perfect solution myself...

I'm convinced such a feature would still be useful and needed, since this problem really still occurs on some recent Android phones: I have some friends, who report to me that, presumably after each Android-Update (=every few months) *unknowingly* their vendor-specific Android version always re-sets the energy-optimization-flag of some Apps such as Signal to the default setting. --> In such cases, they only realize the issue after many days, when they wonder why they don't get Signal messages anymore - that's a pain (for those users Signal only seems "half-working").

**Pull request closed without merging**
