### PR TITLE
Fixes #8870 - Jumbomoji display for emoji 11.0 and 12.0

### LINKED ISSUE #8870: Add Jumbomoji support for Unicode 11 (and 12)
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When using the latest Unicode 11 emojis, such as 🥰 `U+1F970 (Smiling Face With Smiling Eyes and Three Hearts)` or 🥶 `U+1F976 (Cold Face)`, they are not displayed as Jumbomoji.

### Steps to reproduce
- Compose message consisting of a few Unicode 11 characters
- Send message

**Actual result:** 
- Emoji appears in small form

**Expected result:** 
- Emoji should be rendered as Jumbomoji

### Screenshots
Signal bug (2)

### Device info
**Device:** Xiaomi Mi A1
**Android version:** Stock Android 9.0
**Signal version:** 4.41.6

### PR DESCRIPTION
**Pull request by SamLeatherdale**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Xiaomi Mi A1 - Android 9.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
I added the emoji contained in Emoji 11.0 and 12.0 to the EmojiPages file so that they will be displayed as Jumbomoji. Since the Signal fonts do not yet have characters for these new pages, I added a check for missing bitmap in `EmojiProvider.getEmojiDrawable`, which will cause `EmojiProvider.emojify` to fall back to the system's method of drawing the emoji instead of using a custom font.

### CODE REVIEW

**Comment by johanw666** [comment]
This will not solve the issue for older devices,it will still show an empty rectangle (the system's solution). A proper solution would add new pictures as well.

**Comment by SamLeatherdale** [comment]
I don't know what emoji font Signal is using, if you can find out, I'd happily fix the issue for older devices too.

**Comment by mueller-ma** [comment]
Signal uses the emojis by Apple (https://github.com/signalapp/Signal-Android/issues/7644#issuecomment-379523209).

**Comment by SamLeatherdale** [comment]
Thanks, I'll try and add them in. I'll have to categorise the new emoji into the existing categories, so I'll try and follow how Gboard categorises them.

**Comment by greyson-signal** [comment]
Hey, wanna jump in here before it goes too far. The proper way to fix this is to get the updated emoji icons and add them into the app. I have done so locally, and they will be in the 4.44.x release (didn't want to put them in the current beta because I'm trying to get it out the door). 

But just so you have some context, we have big spritesheets in `/assets/emoji` that need to correspond to unicode mappings in `EmojiPages`. This is not something you want to do by hand :) I've created a script to do it, and even then it's a pain. But I appreciate the enthusiasm!

**Comment by SamLeatherdale** [comment]
Hi @greyson-signal, thanks for clarifying. I did actually write a script to grab the unicode characters for Emoji 11 & 12, but I didn't know which font to use, so I didn't proceed that way. 

I also wanted to mention, I noticed that there is a fake version of Signal currently on the Play Store, I have tried reporting it myself, but I thought you guys might want to submit a report yourselves as the developers: https://play.google.com/store/apps/details?id=com.wTheSignal_8929571

**Comment by johanw666** [comment]
> I also wanted to mention, I noticed that there is a fake version of Signal currently on the Play Store

You caught one but there are many. In fact, some company cloned a lot of open source apps, added ads and lets others put them on Google Play to share the bounty. See [this thread](https://community.signalusers.org/t/signal-cloned-apps-in-playstore/3398) for more examples.

**Pull request closed without merging**
