### PR TITLE
Add 5G into README markdown file as a phone data connection.

### PR DESCRIPTION
**Pull request by issafram**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Not necessary (markdown file change only)
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by PrajjwalDatir** [comment]
Why don't You add 2G as well!
I've few friends using Signal through 2G.
@issafram

**Comment by issafram** [comment]
@PrajjwalDatir great idea.  you can put in a PR once this one is merged.

**Review by Relluem94 — APPROVED** [review]

**Review by cassidyjames — APPROVED** [review]

**Comment by JJRcop** [comment]
Pardon me, but all of these cellular technologies may as well be removed altogether, and replaced with `data plan`. It would look quite unwieldy as `(WiFi/2G/3G/4G/4GLTE/5Ge/5G)`, don't you think?

**Comment by issafram** [comment]
@JJRcop We could easily use Ethernet instead of WiFi/cellular.  I'm not trying to enumerate all the different possibilities.
I saw what is currently there and saw the omission of 5G.  So I added it.  Doesn't seem like a big deal to me.

**Comment by JJRcop** [comment]
I understand that you won't enumerate them, but #10519 will add 2G, so we may as well stop before we get that far.

**Comment by issafram** [comment]
Notice how my PR was put in first and most likely someone decided to piggyback off of it.  The maintainers of the repo will ultimately make the decision on the PR.

**Pull request closed without merging**
