### PR TITLE
Fixes placements and directions of two drawables in RTL layout

### PR DESCRIPTION
**Pull request by fumiakiy**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * AVD Pixel API 23
 * AVD Pixel 3a API 30
- [x] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Two drawables appear incorrectly on the media picker activity. Screenshots should be clear enough to tell which ones, but to list:
1. The "playback" triangle on a video media is misplaced
2. The arrow on the "next" button points to the wrong direction

The first issue is fixed in this PR by forcing the view to be always in LTR mode. This may sound incorrect but it is actually correct, that a media playback indicator should not be mirrored in RTL layout. See the [material design documents](https://material.io/design/usability/bidirectionality.html#mirroring-elements) for the description.

The second issue is fixed in this PR by adding the mirrored version of webp drawables.

### Screenshots

|Dir|Before|After|
|---|---|---|
|RTL|mediapicker-rtl-bug|mediapicker-rtl-fixed|
|LTR|mediapicker-ltr-before|mediapicker-ltr-after|

### CODE REVIEW

**Comment by alex-signal** [comment]
Thank you!

This will go out in 5.20

**Comment by Xashyar** [comment]
> The "playback" triangle on a video media is misplaced

Hi @fumiakiy, 

When replying to videos, the playback triangle still looks misplaced, both in Quote-replies and Quote-previews:



----------------------------



Do I need to file a separate issue?

**Comment by alex-signal** [comment]
@Xashyar I'll track this internally, no need to file a separate issue.

**Comment by Xashyar** [comment]
> @Xashyar I'll track this internally, no need to file a separate issue.

Thanks! 👍

**Pull request closed without merging**
