### PR TITLE
Hide Keyboard on Welccome Activity Launch

### PR DESCRIPTION
**Pull request by s4p3r-c1n0s**
… was open previously

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Device TA-1004, Android 9.0.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Review by Relluem94 — APPROVED** [review]

**Review by williamspacefire — APPROVED** [review]

**Comment by itspiaz** [comment]
Correct.

**Comment by s4p3r-c1n0s** [comment]
How does merging work? I just raised a simple bugfix PR and wanted to work on few more things. The last PR merged is dated 19th Nov 2019. Does that mean we are not entertaining open contribution here?

**Comment by s4p3r-c1n0s** [comment]
how can I merge this?

**Comment by s4p3r-c1n0s** [comment]
if someone can merge this as I don't have write access

**Comment by alex-signal** [comment]
Merging is done by us (the Signal devs). I'll run this by the guys today.

**Comment by alex-signal** [comment]
Merged into `5.31`

**Pull request closed without merging**
