### PR TITLE
Add support for typing indicators.

### PR DESCRIPTION
**Pull request by greyson-signal**
Adds the ability to see when other people in the conversation are typing. Opt-in for existing users.

**To-Do**

- [x] Intro screen
- [x] Better enter/exit animation

**Test Devices**
* [Google Pixel, Android 9.0, API 28](https://www.gsmarena.com/google_pixel-8346.php)
* [Nexus 5X, Android 8.1, API 27](https://www.gsmarena.com/lg_nexus_5x-7556.php)

### CODE REVIEW

**Comment by Diapolo** [comment]
Can this be disabled :)?

**Comment by greyson-signal** [comment]
@deutrino No, it won't undo your setting if you re-register within an existing installation. It's also worth noting that this is a setting that can be changed at any time, just like read receipts.

**Comment by glU79z** [comment]
@greyson-signal Considering Signal's privacy first approach the default for new users should also be opt-in and not opt-out. There could be a splash screen after the registration aksing the user whether he/she wants typing indicators and reading receipts which both default to "turn off". If the user wants these features because he knows them from other messengers, he/she will be able to use them directly. If the user is more privacy focused, he/she will also be satisfied by the default configuration.

**Comment by greyson-signal** [comment]
@glU79z I consider this very analogous to read receipts, which we also default to 'on', and I think that makes sense for most users. That said, let's all please keep discussion about this on [the forum](https://community.signalusers.org/c/feature-requests/android-feature-requests). Thanks!

**Comment by hugopilot** [comment]
Wait? This is cancelled?

**Comment by greyson-signal** [comment]
@hugopilot Oh no, just merged into [4.31](https://github.com/signalapp/Signal-Android/commits/4.31) :) I must have forgot to push the rebase before merging, so it didn't detect that it got merged. But it's all good!

**Pull request closed without merging**
