### PR TITLE
CI: Speedups, run tests, upload APK and cleanup

### PR DESCRIPTION
**Pull request by EwoutH**
### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Galaxy S10, Android 10
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Updates and extends the GitHub Actions workflow with the following aspects:
 - Updates to action/checkout v2, which is faster
 - Remove install NDK step, since it's installed by default and speeds up the build
 - Adds an extensive Gradle test job
 - Uploads Arm64 APKs as artifacts on PRs and pushes on Signal's repo, for quick testing
 - Removes a few empty lines

I split up the PR in 3 commits for readability. See the description of each commit for details.

### CODE REVIEW

**Comment by EwoutH** [comment]
The artifact for this PR can be found right [here](https://github.com/signalapp/Signal-Android/actions/runs/482677230) on the run page in the Action tab.

@alan-signal, @greyson-signal and @JLLeitschuh I would like to mention you since you contributed earlier on this workflow, please leave a comment if you have the opportunity!

**Comment by williamspacefire** [comment]
This is really cool, i was looking for this, i was working on something like this but I don't know much of GitHub Workflow, I'll make a PR for my repo, end test ☺️

**Comment by EwoutH** [comment]
@williamspacefire Thanks, more testing is certainly welcome!

**Comment by williamspacefire** [comment]
Thanks, I'll do this right now, everyone testing and helping will make this the best messaging app 🥰

**Comment by williamspacefire** [comment]
Is this if statement needed? If remove it it would work on any repository without the need to change, right?

**Comment by EwoutH** [comment]
I added it to not totally blow up GitHubs servers with unused binaries on everyone's forks. If you need a binary you can remove it manually or open a draft PR.

**Comment by williamspacefire** [comment]
That's right, sorry 😅

**Review by williamspacefire — APPROVED** [review]

**Comment by williamspacefire** [comment]
No, it's cool, you'r right, i didn't think about it, there are to many forks, it would create unnecessary and unused binaries

**Review by paaqp — APPROVED** [review]

**Review by paaqp — APPROVED** [review]

**Comment by alan-signal** [comment]
Thanks for the speed up, I think we'll bring that in. I appreciate the separate commits.

'test' check, well `./gradlew qa` runs the tests already, so that will just cost us money.

And we don't want to upload the APKs as we wouldn't want anyone installing them from Github as those APKs will be signed by a publicly available key. Users should get officially signed releases from the playstore, firebase or our website.

**Comment by EwoutH** [comment]
Thanks for the reply! Glad I could help a bit with the speedup.

`./gradlew qa` executes at this moment 208 tasks, while `./gradlew test` executes 904 tasks. So it seems that there are some tests included in test that are not in qa.

The artifacts are meant for developers that want to test the APK, not for users. They’re hidden quite well so I don’t think users will find them anyways.

**Comment by alan-signal** [comment]
> And the GitHub runners are free as far as I know

Signal operates in a private repo where CI costs money (unless that changed and I didn't notice).

When we cut a release, we push to this public repo.

> The artifacts are meant for developers that want to test the APK, not for users

Developers can build the artifacts, and if they can't, they can't do any development anyway!

> `./gradlew test` executes 904 tasks vs 208

It's going to be running the same tests over and over just in different build types.

**Comment by EwoutH** [comment]
> Signal operates in a private repo where CI costs money

Didn't know that! Can I read more about the different git repos and how they are synced somewhere?

> Developers can build the artifacts, and if they can't, they can't do any development anyway!

Of course they can build it, it's about convenience. With this PR, you can go to github.com on you're mobile device, get the APK and be testing you code changes within 30 secs.

> It's going to be running the same tests over and over just in different build types.

Right, I will remove the test job.

**Comment by alan-signal** [comment]
> Can I read more about the different git repos and how they are synced somewhere?

It's not documented, but we basically operate two remotes on our local git repos and push master to the public remote every release.

> With this PR, you can go to github.com on you're mobile device, get the APK and be testing you code changes within 30 secs.

Plus 8 mins of build time 😂

> Right, I will remove the test job.

Don't worry about it I've already cherry picked what I want from this PR (first commit basically) to the private repo.

**Comment by EwoutH** [comment]
> Plus 8 mins of build time 😂

Which is the perfect time for a nice coffee break! ☕

Anyway, the checkout step is now down from approx. 20 to 5 seconds, and skipping the NDK step saves about 90 seconds. Should shave the build from about 9:45 to 8:00, an easy 18% time reduction :)

**Comment by EwoutH** [comment]
Closing this PR for now, since the speedups are included in https://github.com/signalapp/Signal-Android/commit/577d2b13cac0e93a0f84cd4132d1c16d5e05870c.

I still think uploading APKs on the master branch and on PRs will be very useful for quick testing, however.

**Pull request closed without merging**
