### PR TITLE
Add button to flip camera (front vs rear). Fixes #6279

### LINKED ISSUE #6279: feature request: switching to back camera for video calls
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

It is difficult to point the camera at something other than oneself during a video call using the front camera because it is hard to get oneself out of the way while seeing the screen. It would be helpful to be able to switch between the front and back camera in the call to make it easier to show one's surroundings.

### PR DESCRIPTION
**Pull request by nh2**
### First time contributor checklist

- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [X] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Motorola Moto X (ghost), Android 6.0.1
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

This adds a button to flip the camera (from front to rear) in video calls, in the same fashion as other video call apps have it, and as Signal already has it in its "take-and-send-a-photo" functionality (my change also reuses the same icon from that functionality).

This is a highly requested feature (see #6279 and its many duplicates). I took the time to implement it for my mother and my friends; until now we had a bad time when trying to show things to each other with Signal, because "turning the phone around" to film with the front camera means you can no longer see what you're filming.

I have tested it between my Moto X devices, seems to work quite well.

There are two possible improvements that I would like to discuss; the feature works fine without them but it would be nice to figure out if there's a better way:

* The video preview (on the sender's side) his horizontally flipped when using the back camera. This is a minor UX annoyance. Please let me know how I can flip it. It's the right way around on the receiver's side.
* In `PeerConnectionWrapper.java` I create an additional `VideoCapturer`, `VideoSource` and `VideoTrack` for the rear camera, in addition to the corresponding triple of those for the front camera. This is because I am not sure whether I can swap the underlying hardware device of a `VideoCapturer` at runtime, in which case one triple might be sufficient. Note that, as expected, only one triple is recording at any given time.

### CODE REVIEW

**Comment by MichaelHillcox** [comment]
Built and tested: 
Tested on an Google Pixel XL running Android 8.1.0. When I would try and switch the camera it would simply freeze on the front camera. I've not done any tests but I just wanted to let you know

**Comment by nh2** [comment]
@MichaelHillcox Do you have the possibility and time to debug it with the Android Studio debugger? I would recommend especially checking around these lines https://github.com/signalapp/Signal-Android/pull/7559/files#diff-65bd7b9481c21219b42be9376c95d5ccR109 whether it enters that block.

**Comment by greyson-signal** [comment]
@nh2 Thank you very much for your contribution! I've used this commit as the basis for #7735. :)

**Comment by nh2** [comment]
@greyson-signal Thanks a lot for bringing this across the finish line!

**Comment by nh2** [comment]
@greyson-signal You may want to comment on https://github.com/signalapp/Signal-Android/issues/6279 that this is done because that's where the feature was requested and where the 64 thumbsups are.

**Pull request closed without merging**
