### PR TITLE
Add Mi A1 to hardware AEC blacklist

### PR DESCRIPTION
**Pull request by b0m0x**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Mi A1, Android 8.0.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Adds the Mi A1 to the Hardware AEC Blacklist, as echo canceling does not work, see #7635.

### CODE REVIEW

**Comment by greyson-signal** [comment]
Merged into 4.23 in commit 22905493.
Thank you for your contribution!

**Comment by newuser-web** [comment]
This issue is still on calls with Mi A1 running stock android pie.

**Comment by newuser-web** [comment]
@greyson-signal @moxie0 This issue is still on calls with xiaomi A1 running stock android pie.

**Comment by newuser-web** [comment]
@moxie-signal @moxie0 @greyson-signal This issue is still on calls to this device running stock android pie.

**Pull request closed without merging**
