### PR TITLE
Allow deleting attachments from media overview

### LINKED ISSUE #4242: Allow removing attachments
Please add the possibility of deleting attachments from received and sent messages.

This functionality would benefit usage on devices with limited storage capacity. E.g., my personal situation is that the many pictures and videos I receive are filling up my precious storage space. I would like to delete the pictures but keep the message texts. (Also compare #4065 for a related request to allow storing messages on the external SD card).

### LINKED ISSUE #6111: Wishlist: Possibility to delete images in gallery mode (and when opened)
I have:
- [X] searched open and closed issues for duplicates
- [X] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Feature description
When opening "Image gallery" (or lateron media gallery due to #5941) I would like to be able to multiselect images/media and delete them.
And when opening an image/media, I would like to have the possibility to delete it in this opened view.

Maybe putting this option behind a settings menu as the action bar already contains forward, save, All Images. (In Gallery mode only save).
IMO there should be a dialog, if you really want to delete this (all the selected images).

---
~One point to think about is the corresponding messaged (text).
At the moment, it's only possible to delete the whole messagte (text + image/media) by selecting it right in the conversation.
When deleting in the gallery mode or when opened, the corresponding text is not visible to the user, so maybe it should be contained (with a hint to the deleted image/media)?~[Edit: Duplicate of #4242]

### PR DESCRIPTION
**Pull request by haffenloher**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
* Android 6 and 7.1 emulators
* Android 4.2.2 phone
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Batch-select and delete attachments.

The message itself is currently not deleted (even if it's empty); only the attachment is removed.

Fixes #4242
Fixes #6111

### CODE REVIEW

**Comment by ByteHamster** [comment]
Nice PR!

Is there an indication that the message contained an attachment? Something like a "broken image" icon?

**Comment by haffenloher** [comment]
Nope. This PR is already quite large, so I didn't look into adding placeholders for now.

**Comment by motatuc** [comment]
Thanks for this PR. I hope it will be merged eventually. Tried to apply it manually - it fails with recent builds of Signal. Would you mind adapting it to the latest version?

**Comment by Natanji** [comment]
Could you add a "select all" option in the bar above? This would make it possible to first export all media, then delete them without having to tap every single picture, making for a much nicer UX when you want to shrink the Signal app's database.

**Comment by nrizzio** [comment]
@haffenloher it looks like there are some merge conflicts, could you take a took to see what's going on?

**Comment by quyleanh** [comment]
@haffenloher could you please take a look and solve the conflicts? Thank you.

**Comment by haffenloher** [comment]
Rebased (phew!) and added a "select all" button. Sorry for the delay.

**Comment by PiCob** [comment]
Thanks a lot for your efforts! Just one question: do you think it would be technically possible to (optionally) keep the thumbnail in the conversation (shouldn't take that much space)? So one doesn't lose the whole context... that would be really awesome ;-)

**Comment by ForGorNorPor** [comment]
Does anyone know the status of this PR? Does it only need to be merged by the devs or ist there still any problem with it? I would love to see this in one of the upcoming releases!

**Comment by cgogolin** [comment]
Wow, this would be amazingly useful. Please merge!

**Comment by haffenloher** [comment]
superseded by #7527 :)

**Pull request closed without merging**
