### PR TITLE
Language Changes + better Documentation

### PR DESCRIPTION
**Pull request by GeorgeWalt**
Changed the String if item quantity is 1 to one.

Changed Documentation Name of one section to match.

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [x] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by onovy** [comment]
please use https://www.transifex.com/signalapp/signal-android/dashboard/ for translation, thanks

**Comment by Meteor0id** [comment]
This is not the way to address those issues. Anything specific to a certain language must be edited on Transifex as onovy pointed out.

In German there exist different forms of each numeral word, to conform to gender of the noun following it. Unfortunately it is more complicated to properly implement that in Signal, as other languages have different grammar. One of the developers will have add separate forms on existing strings or separate new strings and add those to Transifex. Currently the abilities of the translation software is limited, which is why these grammatical errors currently exist. Hopefully one of the devs will attempt to add the forms you need in the near future.

It is much more complicated that just editing these strings like you attempted, cause than we would no longer be able to synchronize translations between github and Transifex.

**Comment by RiseT** [comment]
I don't understand what problem these changes are trying to fix.

E. g.

"SMS AN %d FREUND SENDEN" resolves to
"SMS AN 1 FREUND SENDEN",

which is correct German. The same applies to the other changes,

Btw, the mentioned singular forms of these strings used to be something like "SEND SMS TO 1 FRIEND" (instead of "SEND SMS TO 1%d FRIEND") in the past, but had to get changed to using placeholders (mostly because of Eastern European languages, if I remember this correctly).

**Comment by alan-signal** [comment]
Closing. Reason: Translations.

Translations must occur on [transifex.com](https://www.transifex.com/signalapp/signal-android/dashboard/).

**Pull request closed without merging**
