### PR TITLE
Pulled Registration Lock PIN text color up into themes.xml

### LINKED ISSUE #7509: Registration lock reminder has black input field
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
Registration lock reminder has black text in black theme. Very minor issue.

### Steps to reproduce
- Enable the dark theme in Signal
- Have Registration Lock enabled
- Wait for a registration lock reminder where you need to enter your pincode again

**Actual result:** The text is black.
**Expected result:** The text should be white to have sufficient contrast with the black back of the popup.

### Screenshots
screenshot_20180312-174533_01

### Device info

**Device:** OnePlus 3T
**Android version:** 8.0.0
**Signal version:** 4.17.2

### Link to debug log
Forgot to capture, can still provide if necessary.

### PR DESCRIPTION
**Pull request by ianmcderp**
### First time contributor checklist

- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [X] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Honor 7X, Android 7.0
- [X] My contribution is fully baked and ready to be merged as is
- [X] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Pulled text color up into themes.xml, where the light- and dark-theme both have separate text colors for the Registration Lock PIN input field now.

Fixed #7509 Registration lock reminder has black input field

### CODE REVIEW

**Comment by parejadan** [comment]
@ianmcderp the reason have multiple merges in your commit history is because your [original change](https://github.com/signalapp/Signal-Android/pull/7537/commits/832ba4cf73326f546f7cc6c333984239e47a1da6) ended up being conflicted?

**Comment by ianmcderp** [comment]
TBH I don't know what happened to the commit history. I can remember that there weren't any conflicts, but that I might have f'd something up on my local master. Is there anything that I can/shall do about this PR?

**Comment by RiseT** [comment]
I've tested this PR with 4.31.6 and it does what it is supposed to, i. e. it fixes the issue.

@greyson-signal Just 4 lines & the issue it fixes is pretty much right into the face of every dark theme & registration lock user.

**Comment by RiseT** [comment]
I guess this got merged in https://github.com/signalapp/Signal-Android/commit/83479d11b715dadb66eca2069c054b71dcd472df and thus can get closed.

**Comment by RiseT** [comment]
What is still too dark using the dark theme, though, is the "input text", i. e. the string registration_lock_reminder_view__enter_pin ("Enter PIN") which is shown as long as you haven't entered anything. I nearly cannot see it.

**Pull request closed without merging**
