### PR TITLE
Origin message tracing & No forward messages

### PR DESCRIPTION
**Pull request by tesnorindian**
### First time contributor checklist
- [X] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Device A, Android 7
- [X] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
I am raising this PR request to support origin tracing and no forward messages. 

Origin tracing is supported by prefixing the message with the author's mobile number. Apart from this the message is also prefixed with a counter that tracks the number of times the message is sent across the platform. This helps the end user in taking an informed decision on how viral the message is. 

The code is modified to prefix the message body in the following format "+919xxxxxxxxx (x) :"
Where +919xxxxxxxxx is the mobile number of the author for origin tracing
and (x) is the sent counter.

Apart from this the code is also modified to prevent the recipient from forwarding messages that are tagged with #NoForward. 

These changes are done to make Signal compliant with the new Indian IT rules 2021 (https://mib.gov.in/digital-media-guidelines-and-policies). 

Please kindly suggest Signal dev's stand on this.

### CODE REVIEW

**Comment by teynav** [comment]
This could be worst thing you can add to Singal.
1. Not privacy compliant (leaks phone number data)
2. Easily bypassable ( heard copy and paste?)
3. Promotes censorship and tracking user.
4. "#NoForward" or educate the fellow citizen about how to distinguish fiction from reality.
or teach them how to block someone who keeps sending them shit, user should make decision about himself , I don't expect tech to babyfeed me.
5. Signal never reveals how much Signal users are there, so it's impossible to be compliant with that rule which dictates it should apply to 5million + user companies.
6. Signal is totally open source create a custom client for your paranoia 

I don't speak for devs, but this is everything that signals stands against. This is my first PR i ever downvoted. If ever Signal is removed to make dictatorial regime of India happy, I would use Proxy of VPN like fellow people of Iran.

**Comment by clauz9** [comment]
this is a joke right ? you probably have a different date for April Fools or something... 
because if India is going ahead with that dumb law, it's just gonna end up in the same category with Iran, and Myanmar, and other countries where you have to go thru hoops to use Signal, that's all, it's definitely not going to be the other way round.

**Comment by tesnorindian** [comment]
There are big gaps in the new Indian IT rules 2021 and there is no doubt about that. But that is not the debate here. It is about how to improve Signal. 

I would like to disagree with @teynav 

> Not privacy compliant (leaks phone number data)

We have been leaking other's messages in the name of forward for quite sometime now (where is the privacy here?). But while leaking we choose to hide certain important details like the author of the message which is the very reason why we are in a big mess now. We anyway provide our mobile number as part of the Signal registration process. As the recipient of a forwarded message, I have the right to know the author of that message too. Without which I will not be able to trust the forwarded message.Prefixing my messages with my mobile number will help the recipient in taking informed decision. I don't see any breach of my privacy in this process as my messages are forwarded with out my knowledge. 

> Easily bypassable ( heard copy and paste?)

Never saw the behavior of any E-Mail client while forwarding mails? Do you change those E-mail trails? Why are we caring more for criminals and anti social elements who are interested in forging the headers. Not all are sour apples in any community. The law enforcement will deal with those criminals and anti social elements, let's leave it to them. 

> Promotes censorship and tracking user

Not sure how it does. The recipient of a forwarded message is the one who can object to a forwarded message and seek the service of the law enforcement. We are not allowing any interception or breaking of the encryption. 

> "#NoForward" or educate the fellow citizen about how to distinguish fiction from reality.

I would like to share my personal message to a particular group and would expect it to be not forwarded. So you expect me to educate all the 1000 members in that group? Don't I have any other job other than educating each one of them? #NoForward is my intent to the recipients and provides a safety to my message. Nobody expects tech to baby feed, so only I tag my messages to safeguard it from being forwarded and the client disables forward button for such tagged messages. Business E-Mails have this feature for quite sometime now.  Disappearing and view once messages doesn't serve this purpose and are intended towards a different target audience.

There is nothing joke in this, We have to ensure that the platform is not misused by criminals and anti-social elements. Critics are welcome but not criminals.

**Comment by johanw666** [comment]
>  It is about how to improve Signal.

No, it's about supressing opinions that the current Indian government does not like. They are far too authoritarian and engaged in multiple conflicts where they want to stiffle discussion (farmers uprising, Kashmir, border conflict with China, trying to eradicate the use of "Indian variant" of the cortonavirus).  I don't want to take side in these conflicts but opposition against the official truth needs to be discussed freely.

> As the recipient of a forwarded message, I have the right to know the author of that message too.

No you don't, that depends on what the sender decides. Maybe the sender decides it is too dangerous for the original source to become known to you. For example, when I discuss Indian policy with you I can do freely becuause the chance that India will arrest me for it in the EU is negligible. But when I want to quote Indian sources I prefer to protect their identities for government agents.

**Comment by tesnorindian** [comment]
Will masking the last few digits of the mobile number help? I know the number of digits to mask will become a debate. But there is a delicate balance we need to maintain. Critics are always welcome.

**Comment by teynav** [comment]
> We have been leaking other's messages in the name of forward for quite sometime now (where is the privacy here?). But while 
leaking we choose to hide certain important details like the author of the message which is the very reason why we are in a big mess now. We anyway provide our mobile number as part of the Signal registration process. As the recipient of a forwarded message, I have the right to know the author of that message too. Without which I will not be able to trust the forwarded message.Prefixing my messages with my mobile number will help the recipient in taking informed decision. I don't see any breach of my privacy in this process as my messages are forwarded with out my knowledge.

It's interesting that this is how you think privacy works :") .

> Privacy is the ability of an individual or group to seclude themselves or information about themselves, and thereby express themselves selectively. 

Signal by design is secure, and employs privacy practices like hiding online status etc. Signal can't stop what you do with end information and Signal doesn't have to due to "plausible deniability" of message. It's open source and the database can be modified at your will on your side, how can you prove that he said this when you can modify it to anything else. Please be educated on topic you are talking about. It however risk of information leaking to other clients 

> Never saw the behavior of any E-Mail client while forwarding mails? Do you change those E-mail trails? Why are we caring more for criminals and anti social elements who are interested in forging the headers. Not all are sour apples in any community. The law enforcement will deal with those criminals and anti social elements, let's leave it to them.

Another lack of knowledge, you comparing email to Signal. Email was designed to be neither safe nor privacy compliant protocol, so your comparison is flawed. If you think email does your job, maybe signal isn't for you.

>Not sure how it does. The recipient of a forwarded message is the one who can object to a forwarded message and seek the service of the law enforcement. We are not allowing any interception or breaking of the encryption. 

As you know there exists copy and paste, you wouldn't copy the "phone number" but content of message when it's done, so this is how it's easily bypassable in even your dystopian regime. There are many thing that won't break end to end encryption like uploading user's gallery on each message, shouldn't mean you should do it. When I type my message, It should go as it is not without any tracking/extra information. It seems like you clearly don't understand what privacy means either.

> would like to share my personal message to a particular group and would expect it to be not forwarded. So you expect me to educate all the 1000 members in that group? Don't I have any other job other than educating each one of them? #NoForward is my intent to the recipients and provides a safety to my message. Nobody expects tech to baby feed, so only I tag my messages to safeguard it from being forwarded and the client disables forward button for such tagged messages. Business E-Mails have this feature for quite sometime now. Disappearing and view once messages doesn't serve this purpose and are intended towards a different target audience.

You know how Signal works right? Any custom client can bypass it, any i say. This provides 0 use case, people would migrate to custom client. 0 use case because due to plausible deniability no-one can say this was your message.

> Will masking the last few digits of the mobile number help? I know the number of digits to mask will become a debate. But there is a delicate balance we need to maintain. Critics are always welcome.

Now if you don't know Signal would move from phone number identifier to username, and you  would have option to be not be discoverable by your username. 


Signal is "open market" you think your idea is special and is much better, create your own fork like Molly, do whatever I consider dystopian and see where you can go with it. Whatever you are trying isn't private, and not even ensure the correct behaviour ( anyone with  another custom client and say message deemed offensive in your regime and tag a forward message by some adversary, so he gets in trouble by your stupid idea :") )

**Comment by johanw666** [comment]
> 
> 
> Will masking the last few digits of the mobile number help? I know the number of digits to mask will become a debate. But there is a delicate balance we need to maintain. Critics are always welcome.

There is only one acceptable number of digits: 0.

**Comment by greyson-signal** [comment]
To start, please treat everyone with kindness and respect here. Not liking someone's idea isn't an excuse for rudeness.

Concerning this PR, I don't think it aligns with Signal's privacy goals. But thank you!

**Pull request closed without merging**
