### PR TITLE
Add fast scroller to conversation view

### LINKED ISSUE #6095: Calendrical fast scrolling for conversation view
I have:
- [x] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
With the introduction of (sticky) date headers, it would make sense to add fast scrolling to the conversation view (like the alphabetical fast scrolling in Signal's contact list, but with dates instead of alphabetical characters).

### PR DESCRIPTION
**Pull request by haffenloher**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * AVD, Android 7.1.1
 * Stupid MT6589 phone, Android 4.2.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

Fast scroller showing the same text as the new sticky message headers.

screenshot from 2017-01-26 17-39-56
screenshot from 2017-01-26 17-40-15

Fixed some glitches I encountered with the fast scrollbar along the way.
I verified that the contact selection list's fast scroll bubble looks unchanged with this PR.

I had to move the new "scroll to bottom" button to the left because it interfered with the scroll bar handle.

Fixes #6095
Currently only enabled for convos with >20 messages - somewhat related to #4778

### CODE REVIEW

**Comment by Stuie** [comment]
I think moving the scroll to bottom button to the left makes it unusable for single-hand use cases for right-handed people (the majority).

If we don't care about that then fine. :)

**Comment by RiseT** [comment]
Don't know if my hands have some strange anatomy, but I (right-handed) actually find it easier on a Nexus 5X to reach to the left side with my thumb than to the right side...

**Comment by haffenloher** [comment]
Problem is, with the old positioning, you'd accidentally activate the scroll bar handle all the time when wanting to press the button (if the handle is near the bottom). Other ideas welcome!

**Comment by RiseT** [comment]
I feel that the right side is slightly crowded anyway.

What you could potentially do is moving the floating bottom a couple of pixels to the right (e. g. center it with the avatar pictures). But this changes things only slightly.

Don't know if horizontally centered (relative to the display) floating botton would make any sense design-wise. Just a random thought.

**Comment by Stuie** [comment]
Having it towards the bottom probably helps to make it reachable for most people, but there are definitely much larger phones than the Nexus 5X.

As a left-handed user I encounter issues interacting with buttons over on the right, above a certain height. On my old Nexus 6 it was quite annoying to tap the scroll to bottom button in WhatsApp/Telegram, but I assume they picked that side for a reason.

**Comment by haffenloher** [comment]
@RiseT centered looks good to me:

screenshot from 2017-01-26 21-15-36

**Comment by RiseT** [comment]
Perfect. Uncrowded area and easily reachable for both right- and left-handed users.

**Comment by RiseT** [comment]
Somehow off-topic: Would Signal benefit from a left-hand mode which mirrors the user interface...? Just tossing this in as an idea.

**Comment by Stuie** [comment]
Android in general would benefit from left-handed support, implemented similarly to right-to-leftlanguage support, perhaps.

I quite like the button being in the middle...

**Comment by p4nci** [comment]
hmmm 🤔 , in the center we have already date headers, so it's a little bit "overpopulated" there (???). Further when rotating in the landscape mode the button will change position and might not be optimal.

IMO:
```
IF possible to implement:
   let the scroll button as is (right bottom position)
   set scroll button to HIDDEN if "fast scroller" in use,
   otherwise set to VISIBLE
ELSE
   remove the scroll button (still possible to jump to the bottom with "fast scroller")
```
I think there is no need for both buttons (scroll + fast scroll) at the same time

**Comment by RiseT** [comment]
The sticky/floating date header is on the top of the display, while the "scroll to bottom" button is on the bottom.
How can this be overpopulated?

On the right side, there are already elements for quick camera, voice messages, attachments, phone calls, the 3-dot-menu and the scroll bar (including fast scroll).

**Comment by haffenloher** [comment]
> set scroll button to HIDDEN if "fast scroller" in use

@p4nci see above - the problem occurs when the scroll bar handle is next to the button. The button then becomes almost impossible to hit with a finger (the scroll bar gets mistakenly activated instead).
Also keep in mind that the button is hidden by default. It appears after you scroll up a bit (after ~5 messages).

**Comment by p4nci** [comment]
> The button then becomes almost impossible to hit with a finger
> (the scroll bar gets mistakenly activated instead).

that's a good point. IMO in this case it's better to remove the scroll button (see above - ELSE) => the "fast scroller" is still sufficient for scrolling and "jumping" to the bottom

> The sticky/floating date header is on the top of the display,
> while the "scroll to bottom" button is on the bottom.
> How can this be overpopulated?

I know, but there are two centered "buttons"(top: date header bubble + bottom: scroll button, which shows up/disappears async.) and that is too twitchy (="overpopulated" 😉) IMO

**Comment by AlfonsoMuskedunder** [comment]
> I know, but there are two centered "buttons"(top: date header bubble + bottom: scroll button, which shows up/disappears async.) and that is too twitchy (="overpopulated" :wink:) IMO

@p4nci Apparently the date header is already invisible when using the fast scroller. Only when scrolling "regularly" will it appear. So that's not a source for clutter.

I agree though that the scroll-down button might be a little redundant once the fast scroller is activated, independent of where it's placed.

**Comment by motatuc** [comment]
>I agree though that the scroll-down button might be a little redundant once the fast scroller is activated, independent of where it's placed.

I agree as well. The question is if we still need the scroll-down button once we have fast-scrolling...

**Comment by motatuc** [comment]
Tested fast scrolling and it works nice. The size of the bubble is a bit intense though... However the scoll-to-bottom button is now somehow in the middle of the screen. Is there already a decision made about which of the two features to use?

**Comment by moxie0** [comment]
hmm i don't really love the idea of having the scroll-to-bottom button in the center of the screen

**Comment by haffenloher** [comment]
@moxie0 okay, on the left it is

**Comment by p4nci** [comment]
I still believe that the best solution is without scroll-to-bottom button

**Comment by motatuc** [comment]
I would also vote for the remove of the scroll-to-bottom button if fast scrolling is accepted.
Two reasons: a) Both features basically provide the same feature (fast scrolling) and b) fast-scroller is faster and works in both directions.

**Comment by RiseT** [comment]
All I can say is that personally, I don't tend to use those scroll-to-bottom buttons. But that's just me. Don't know about others or the "average user".

**Comment by Stuie** [comment]
I use search to scroll back to a specific message. I generally don't need to go to a specific date, but rather a specific message, and then one button takes me to current.

Personally I believe this should be a data-driven decision, but I'm not sure what requirements @moxie0 has for analytics/metrics collection, what with the inherent privacy concerns of this project.

Ideally we would split test both features to determine the right option.

**Comment by Stanzilla** [comment]
Agree with @motatuc here, also the PR was originally about fast scrolling, if anything a scroll to bottom button should be a separate PR.

**Comment by zoff99** [comment]
when is this going to be merged? i already made a PR for fastscroller which was dismissed.
it's crazy that this is taking so long.

**Comment by haffenloher** [comment]
Rebased. Fixes for the fast scroller glitches I found are now in #6149.

**Comment by hklene** [comment]
The screenshots really look great - Is it still possible to resurrect this or will it have to be rewritten from scratch?

**Pull request closed without merging**
