### PR TITLE
Added an option that prevents blocked contacts to add you to a group

### PR DESCRIPTION
**Pull request by johanw666**
and if they do auto-unsubscribe and delete the group

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Samsung A50, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

For several days members of some public Signal groups are harassed by a stalker that endlesly adds them to newly created groups with insulting names. Blocking the stalker is of nomuse because he can still add you to a group.

This PR adds an option in the Chats section of settings that, when switched on, prevents any blocked person from adding you to a group. If the person tries it you will leave the group automatically and the group entry in the conversation list is deleted.

### CODE REVIEW

**Comment by Tursko** [comment]
Should this really be an option? I feel like it should be part of blocking someone in general.

**Comment by hiqua** [comment]
See https://community.signalusers.org/t/beta-feedback-for-the-upcoming-android-5-32-release/41638/285?u=hiqua for context / answer

**Comment by johanw666** [comment]
> Should this really be an option? I feel like it should be part of blocking someone in general.

I tried to give this PR a default behaviour that acts the same as Signal does now. But removing the option part is very easy, then just the changes in GroupsV2StateProcessor.java remain, without the check for the option being set.

**Comment by clauz9** [comment]
@greyson-signal is there any interest in this PR around the virtual Slack watercooler at Signal ? 😄   

I, along with other people have just been added to a few groups again, and it's not pleasant.
I don't know if that "abusive message filter" is supposed to do something about this or not, but it's probably safe to say, that it's currently not doing much.

**Comment by johanw666** [comment]
OK, I merged in latest master and expanded the option so you can now control who can add you to groups:

signal-group-block

**Comment by clauz9** [comment]
I suppose you can close this one ... 🤔 right ?

**Comment by greyson-signal** [comment]
Yeah, we can close this now that we've merged in a change that prevents people you've blocked from adding you to groups.

**Pull request closed without merging**
