### PR TITLE
show remaining duration of audio messages during playback

### PR DESCRIPTION
**Pull request by duchampdev**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * BQ Aquaris X, Android 8.1
 * Google Pixel 3a, Android 10
- [x] My contribution is fully baked and ready to be merged as is.

----------

### Description
Already often, I heard from other users that they would like to see how long a given audio message will (still) play. So I took the field already present in the code and populated it with the remaining duration ~~current playback position of the audio message complemented by its full duration~~.

### CODE REVIEW

**Comment by duchampdev** [comment]
Respective Feature Request in the forum: https://community.signalusers.org/t/add-length-to-voice-message/2731

**Comment by duchampdev** [comment]
This PR was updated to resolve conflicts which occurred since the PR was initially created.
Furthermore, the displayed time is now the remaining time to resemble the behavior on iOS.

**Comment by Pentaphon** [comment]
Any progress with this? It seems simple enough to add.

**Comment by duchampdev** [comment]
This is now implemented in upstream, so closing this.

**Pull request closed without merging**
