### PR TITLE
Fixed bug where contacts sync would break on new contact added

### LINKED ISSUE #11236: Signal contact sync breaks after adding a new contact
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal doesn't show up (disappears) in contact apps nor when queried using `ContentResolver`.  
Normally, when you query contacts using `ContactsContract.RawContacts.ACCOUNT_TYPE` you should be getting the package name associated with a contact (the app used to sync the contact, for example Google/WhatsApp/Signal)
```
        /**
         * The type of account to which this row belongs, which when paired with
         * {@link #ACCOUNT_NAME} identifies a specific account.
         * <P>Type: TEXT</P>
         */
        public static final String ACCOUNT_TYPE = "account_type";
```
But it seems that after adding a new contact Signal just disappears or removes all its contacts.   

Uninstalling -> reinstalling the app/clearing the app data temporary fixes the issue, but it occurs again after adding a new contact.  

This commit seems to have introduced the bug: https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97

### Steps to reproduce

- Make sure sync is enabled for Signal and that your contacts are synced correctly
- Add a new contact
- Open Signal
- Got to settings and manually sync Signal if auto sync is disabled
- Open contacts app and open a contact that has Signal
- See that it doesn't have Signal as a communication method

**Actual result:** Signal stops showing up in contacts/Signal contacts stop sync
**Expected result:** Signal shouldn't stop syncing contacts/contacts shouldn't disappear  

### Bad behavior:
Screenshot_20210426-181552_Contacts
Screenshot_20210426-181557_Contacts

### Good behavior (after clearing the app data)
Screenshot_20210426-181926_Contacts
Screenshot_20210426-181929_Contacts

### Device info

**Device:** Galaxy S10
**Android version:** 11
**Signal version:** 5.9.3

### Link to debug log

Logs are irrelevant, I found the line that causes this bug, I ran it and debugged it, the issue happens when adding less than 10 contacts and running sync, in my testing I added 1 contact leading me to `There are 1 unknown contacts..` log. You can follow the flow from here:
https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97#diff-6c090eefdf3ea4ba7d7c39fa0e3e2488facaa234c7ac3f27b122af3184fd6b56R64

But I saved you the trouble, the problem line is this: https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97#diff-973ca3d23ec70a73c09dc70e4b40e97e26988696392dcdd8f446468db7a96db2R269

Specifically passing `true` to the function, in this case, when providing only one recipient for example, this function will remove all pre-existing contacts

### PR DESCRIPTION
**Pull request by rosenpin**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Galaxy S10e, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` syntax

----------

### Description

Quick fix for https://github.com/signalapp/Signal-Android/issues/11236  
@alan-signal and @greyson-signal introduced a bug in https://github.com/signalapp/Signal-Android/commit/fcc49ae7b6958777158a7daecb7a9d6797d5da97 that causes all Signal contacts to disappear after adding a new contact, this PR fixes this bug.  
The reason for this bug was that they used a function that takes phone numbers, in this case only 1-9 phone numbers were passed, the function used removes all phone numbers not included in the passed numbers argument (in other words, all previous contacts)

Note: there might be some implications to this change that I don't understand as I don't have a good grasp on the code base, it would be great if you could double check me and let me know if any other changes are required 

This PR fixes #11236

### CODE REVIEW

**Comment by rosenpin** [comment]
You should probably merge and push this fix ASAP, since every day another user creates a new contact and looses all of his Signal contacts  
My merge request doesn't revert this deletion, it only fixes it so it won't happen again. Since fcc49ae syncing manually or automatically will never sync all contacts (except if more than 10 contacts were added before the sync, which for most users will never happen), meaning users affected by the bug fixed in this PR will not be able to restore their contacts.  

You should probably create an additional patch (after pushing this update ASAP) that checks if no contacts are synced and in this case does a full sync once.

**Comment by rosenpin** [comment]
Has this been addressed in a different commit?  
If not, what's the hold up?

**Comment by rosenpin** [comment]
@cody-signal @alan-signal @greyson-signal 

Did you already solve this issue? If so, I'll close this PR

**Comment by greyson-signal** [comment]
Hi there! Just merged this into our 5.13.3 branch (with some minor tweaks) that will go out soon. Thanks!

**Comment by rosenpin** [comment]
> Hi there! Just merged this into our 5.13.3 branch (with some minor tweaks) that will go out soon. Thanks!


relevant issue https://github.com/signalapp/Signal-Android/issues/11236

Also, bummer that you couldn't use my PR so I could get the appropriate credit :(

**Comment by greyson-signal** [comment]
Oh don't worry you still have authorship. The way Github PR's are setup aren't conducive to how we do releases, but we always make sure people keep authorship in their commits.

**Comment by greyson-signal** [comment]
1eae36047094cb5c14c5e8e5864184b6b3efeae2

**Pull request closed without merging**
