### PR TITLE
Fixes #9341, better version of #9692. Adds unicode wildcards for equivalent latin characters

### LINKED ISSUE #9341: Upper- and lowercase accentuated characters are considered different when searching for a contact
- [x] I have searched open and closed issues for duplicates
  

---

### Bug Description

As in the title : when either searching for a term in a conversation, or a recipient to send a message to, accentuated uppercase charactres (e.g. "É") are considered different than the same accentuated but lowercase character (e.g. "é").

Language is french.

### Steps to Reproduce

1.  Open Signal
2.  Tap the "Search field"
3.  Type (for instance) "éric"

Actual Result:

My contact "Éric" is not shown.

Expected Result:

My contact "Éric" is shown.
I need to explicitely type "Éric" (or "ÉRIC", or any other upper/lowercase combination except for "É")
Also, typing "eric" or "Eric" or "ERIC" (etc.) should also display "Éric".

### Platform Info

Signal Version:

Signal 4.52.4
Not sure about Signal Desktop.

Operating System:

Android 9 (LineageOS 16)

Linked Device Version:

### PR DESCRIPTION
**Pull request by Karalix**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist
- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Xiaomi Mi 9 Lite, Android 9
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

So in PR #9692 the key point I was trying to address was that accentuated char should be considered when typing unaccentuated chars when searching for a name (eg. "eric" should return ["Éric", "Albéric"]). Right now, even with commit 5bf15b0, the search function is hardly usable in french and many other accentuated languages.  @greyson-signal pointed out that my solution was limited to a very narrow subset of unicode. That was very true, at that time I focused only on baguette-eating accentuated characters.

I understand that Signal is used everywhere around the world so here is an improved version of the proposal that matches similar characters from the following unicode blocks :
* [Latin-1 Supplement](https://en.wikipedia.org/wiki/Latin-1_Supplement_(Unicode_block))
* [Latin Extended-A](https://en.wikipedia.org/wiki/Latin_Extended-A)
* [Latin Extended-B](https://en.wikipedia.org/wiki/Latin_Extended-B)
* [Latin Extended Additional](https://en.wikipedia.org/wiki/Latin_Extended_Additional)

to achieve that result, I make an extensive use of regex with hand-picked character ranges. It was a soul crushing task, 0/5 do not recommend.

screenshot-signal

### CODE REVIEW

**Comment by Karalix** [comment]
So a friend of mine spotted a typo and we though of a better testing procedure that allowed us to uncover 4 typos in my previous commit.

In brief we built a visually structured test string from the unicode blocks and tested each regex using regex101. This process allows a quick visual verification of the regex validity. Here is the regex101 link already setup if you want to try by yourself : https://regex101.com/r/vaN0J8/1

**Comment by Caerbannog** [comment]
As another French user this feature/improvement is something that annoyed me too. Thanks @Karalix for working on it.

For reference here are related topics by other users:
- Community: https://community.signalusers.org/t/contact-search-could-be-fuzzier-about-unicode-diacritics/9252
- Old issue (closed): https://github.com/signalapp/Signal-Android/issues/6499

**Comment by Caerbannog** [comment]
I have compiled and tested this PR on the following device:
* Xiaomi Mi A2, Android 10.

It works as expected.

**Review by Caerbannog — APPROVED** [review]

**Comment by Karalix** [comment]
I am sure the Signal team is already busy with a lot of other things, but could we at least get a quick heads up regarding this issue ? This usability problem has been there for years now.

Can we expect you to take a look in the near future ? Or should we consider it is not on your roadmap at all for the moment ? Thanks for all you've already done with Signal

**Comment by Caerbannog** [comment]
@cody-signal @greyson-signal This PR represents a massive improvement of contact search for many languages.
French, Greek, German, Cyrillic languages, ...

It is a problem new users notice quickly.
Some of my friends have names with accents, but for 50% of them I haven't bothered to save the accent. So searching for them in Signal is a lottery.

**Comment by greyson-signal** [comment]
This looks great and doesn't seem to have any noticeable perf impact. Thank you @Karalix very much for taking on the task of finding all of the equivalent characters :)

I've merged this into our 5.9.1 candidate branch, which will be released shortly!

**Pull request closed without merging**
