### PR TITLE
Do not disturb option in settings, to block all incoming calls

### PR DESCRIPTION
**Pull request by IdeasMX01**
### First time contributor checklist

- [x ] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x ] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x ] I have tested my contribution on these devices:
 * Huawei Y6, Android 9
 * Samsung S7, Android 8
 * Virtual device Google Pixel 3, Android 10.0
- [ x] My contribution is fully baked and ready to be merged as is
- [x ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
Adds "Do not disturb" option in settings, to block all incoming calls. Useful if you receive many signal calls, and you need to block them for a while.

### CODE REVIEW

**Comment by Eldenroot** [comment]
Also would be great tonadd these features from whattsapp:

- global mute notifications for all contacts from home page list of conversations
- mute notifications (sounds and vibration) but display notifications about new messages

**Comment by IdeasMX01** [comment]
Hi, I want to know if there's something missing or what is the next step to close this pull request?

**Comment by IdeasMX01** [comment]
Yes, it's relevant, but I  don't know what the next step or who is the person who accept the pull request to change the status to complete.

**Comment by IdeasMX01** [comment]
I don't have permission to merge pull request, so, can somebody do it please?

**Comment by IdeasMX01** [comment]
@greyson-signal I found you in the contributors list, I apologize for taking your time, but do you know how can I proceed with my request?

**Comment by IdeasMX01** [comment]
I don't know what is the benefit of contribute if noone answer you about your PR?
I'm frustrated because of that. @Eldenroot @greyson-signal

**Comment by Eldenroot** [comment]
Thats why I dont understand this project anymore...

**Pull request closed without merging**
