### PR TITLE
 added functionality to replace images by lower resolution versions

### PR DESCRIPTION
**Pull request by MarcSN311**
### First time contributor checklist
- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual Pixel XL, Android 8.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
This adds an "Archive" button to MediaOverviewActivity and MediaPreviewActivity. "Archiving" an image replaces it with a very low resolution version, "Archiving" a video replaces it with a very low resolution thumbnail.
This allows the user to slim his Signal installation down, without breaking context as deleting the image (and corresponding message) would.
It is also a possible fix for this feature request: https://community.signalusers.org/t/2680

### CODE REVIEW

**Comment by bemasc** [comment]
This feature is exactly what I need right now.  I wish it would get more attention.

**Comment by tjaalton** [comment]
Yes it is relevant, because right now the app db will just balloon without limits, and it's bad to just remove the media as you'd then lose the message content as well

**Comment by MarcSN311** [comment]
I am absolutely willing to resolve the conflicts and make my PR compatible with the current Version. Sadly the Signal Team doesn't seem to be interested.

**Comment by MarcSN311** [comment]
Yes still relevant. I am absolutely willing to fix the conflicts if Signal team is interested in merging.

**Pull request closed without merging**
