### PR TITLE
Only force stop audio player when leaving conversation

### LINKED ISSUE #8462: Signal allows device to sleep while playing audio
- [x ] I have searched open and closed issues for duplicates
- [x ] I am submitting a bug report for existing functionality that does not work as intended
- [x ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When a signal user plays an audio file in that another signal user has sent them inside the signal app, signal does nothing to prevent the device from "going to sleep" or turning the screen off while the audio is being played.  If a user tries to play a clip that's longer than ~30 seconds (or whatever the timeout is configured to be), the audio clip will pause and the user will need to unlock the phone to continue playing the audio clip.

### Steps to reproduce
- Receive a long (longer than the screen timeout; try any song 2 minutes or more) audio file in signal
- Play the audio file in signal
- Don't touch the phone, just try to listen to the whole file

**Actual result:** Phone screen shuts off and also pauses audio playback
**Expected result:**  phone should not go to sleep during audio playback - audio playback should continue until end of file

### Screenshots
Not necessary

### Device info
Google Pixel XL 128GB
Android 9 (December update)
Signal 4.31.6 (installed from Google Play)

### Link to debug log
this is not necessary (but let me know if you somehow cannot reproduce this - would be happy to help!)

### PR DESCRIPTION
**Pull request by dwong**
Fixes #8462

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
  * Virtual device Pixel 2 XL, Android 8.1
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

Only force stop the audio player if the user is leaving the conversation so that if the user plays an audio file and turns off the screen then the audio file continues to play.

Tested this by sending a music file and trying the following scenarios:

- Normal Play
  1. Play file
  2. Stop file
  3. Play/pause button behaves as expected
- Play With Screen Off
  1. Play file
  2. Turn off screen with power button
  3. Audio continues to play
  4. Turn screen on
  5. Play/pause button behaves as expected
- Leave Conversation While Playing
  1. Play file
  2. Leave conversation with back button
  3. Audio stops
  4. Enter conversation again
  5. Audio playback resets to beginning

### CODE REVIEW

**Comment by Xashyar** [comment]
@dwong Would this PR also prevent audio from playing when the phone gets locked?

**Comment by dwong** [comment]
@Xashyar yes the audio continues to play when the screen goes to sleep.  Is that what you mean?

**Comment by Xashyar** [comment]
> 
> 
> @Xashyar the audio continues to play when the screen goes to sleep. Is that what you mean?

Yes, hope it gets merged soon! 
Is this the only thing this PR is supposed to achieved?

**Comment by Xashyar** [comment]
> 
> 
> @Xashyar the audio continues to play when the screen goes to sleep. Is that what you mean?

Yes, hope it gets merged soon then! 
Is this the only issue/scenario that this PR is addressing?

**Comment by dwong** [comment]
@Xashyar basically yes

**Comment by Xashyar** [comment]
> 
> 
> @Xashyar basically yes


Currently scrolling over a playing audio, also would make the audio stop. So with this PR in mind, the audio would keep playing still, even after being scrolled over and the only way to shut it down would be leaving the conversation or closing the app altogether (which results in the loss of last scroll position, See), @dwong Can you also confirm whether that would be the case? 

Thanks.

**Comment by dwong** [comment]
@Xashyar I don't know what you mean by "scrolling over a playing audio".  Is there a ticket?

**Comment by Xashyar** [comment]
> @Xashyar I don't know what you mean by "scrolling over a playing audio". Is there a ticket?

If you play an audio (either from Storage view or within a Chat) and then you scroll up or down so it (the playback box) gets out of the screen, then it would cause the audio to stop playing.

**Comment by dwong** [comment]
@Xashyar tried this with both current Android Signal 4.52.4 and with my fix and they both continue playing the audio after I scroll past the player in the Chat.  Can you create a ticket with more detail?

**Comment by thomaseizinger** [comment]
Thank you for working on this @dwong !

Does the proposed behaviour also apply to voice messages or just audio files being sent?
Would you mind having a look at [my comment](https://github.com/signalapp/Signal-Android/issues/8462#issuecomment-573374436) on the original issue?

**Comment by dwong** [comment]
@thomaseizinger responded in the original ticket but will here as well: they're just audio files so the fix will apply the same way

**Comment by Xashyar** [comment]
It's worth noting that this issue existed in iOS https://github.com/signalapp/Signal-iOS/issues/3894, and has got resolved in the subsequent updates, right now iOS even allows background playbacks (i.e. audio continues playing after the app gets minimized) and also playback navigation widgets.

**Comment by greyson-signal** [comment]
This isn't quite how you'd want to do this. It doesn't quite fit in with the Android app lifecycle, and just wouldn't work in some scenarios. If we wanted to allow playback when the app isn't focused, we'd want to switch to running audio playback in a service that can be presented as a foreground notification (and allow playback and scrubbing and stuff).

**Comment by dwong** [comment]
@greyson-signal Would #8470 be an appropriate fix or should I leave that closed as well?  I had closed that one in favor of this one.

**Pull request closed without merging**
