### PR TITLE
Keyword-based antispam

### PR DESCRIPTION
**Pull request by annabeth-h**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Samsung Galaxy A3 , Android 7.0
 * Samsung Galaxy S8, Android 7.0
- [x] My contribution is fully baked and ready to be merged as is
- [] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
This feature allows to user enter some words so that received messages containing that words never appear in the app. You can find it in privacy settings > privacy > muted words.

### CODE REVIEW

**Comment by moxie0** [comment]
1. It seems like the bulk of this diff is the introduction of a dependency, "androidtagview," by copying the code directly into the repo. I'm not sure what androidtagview is, but please use a versioned maven artifact for dependencies.

2. It looks like you've introduced a new database table. Please follow the conventions the rest of the code uses for the creation and management of that table.

3. Are they "muted" or "blocked" words?

4. Is this really a problem that people have?

**Comment by Pernat1y** [comment]
>> 4. Is this really a problem that people have?
Yes.

**Comment by Pernat1y** [comment]
> 4\. Is this really a problem that people have?

Yes.

**Comment by alan-signal** [comment]
Closing. Reason: CLA not signed.

You have not signed the [Contributor License Agreement](https://signal.org/cla/).

Also, too many conflicts and feedback from Signal not addressed.

**Pull request closed without merging**
