### PR TITLE
Enable Chromebook support (Addresses #7377, #7357)

### PR DESCRIPTION
**Pull request by fat-tire**
image

Around 15 November 2018, the Signal Chrome extension expires, leaving millions of Chromebook owners without the ability to use Signal for secure communication.  And yet

* In 2017, Chromebooks made up [59% of mobile devices shipped to US schools](https://www.usatoday.com/story/money/markets/2018/04/10/foolish-take-u-s-schools-love-chromebooks/498974002/)

* By January 2018, [25 million student alone use a Chromebook at school](https://www.androidcentral.com/chromebooks-education-everything-you-need-know
)

IT GOES WITHOUT SAYING, ABANDONING CHROMEBOOK USERS IS *NUTS*!

image

This patch enables Signal for Android to run decently on Chromebooks.

*  Because most (all?) Chromebooks do not have mobile service, they cannot receive SMS directly.  Therefore, you will probably have to verify your phone number by entering the confirmation code sent to your phone.  This is similar to running on an Android tablet.

*  Signal currently allows only *1* Android device per phone number. See [here](   https://support.signal.org/hc/en-us/articles/360007320451-Troubleshooting-multiple-devices
).  So if you already use Signal on your phone, you will have to use another number (such as a Google Voice number available with your Google account) to set up Signal on Chromebook.

*  On the bright side, you get audio + video calls on your Chromebook!

*  Windows are re-sizable and the top window is not destroyed by escaping or hitting back (You can hit ^W to close it, however).  You also get multiple windows in newer development versions of ChromeOS, which is kind of cool.  File transfers, GIFS, and other basic features work well.

*  Chromebooks and QWERTY-keyboard devices enable the "Enter sends" preference by default, so that hitting the keyboard ENTER/RETURN will send the message (rather than add a linefeed).

*  If you run into build issues, look at Issue #8329 for a solution.  This currently builds successfully for me on Android 3.4 canary in Linux(though I'm sure it will build on older versions) with the easy #8329 fix that may not be needed on those older Android Studios.

NOTE:  Without this commit, there is currently no acceptable upgrade path for most current Chromebook owners. Although some CBs can run the standalone Desktop version via a "Crostini" Linux container, this is neither as lightweight nor as [available](https://www.androidpolice.com/2018/08/22/google-confirms-many-older-chromebooks-wont-get-linux-apps-including-2015-chromebook-pixel/) as an Android solution.  (In the future, the Android client should be able to be run on the same account with the user's phone. But that's another commit altogether...)

### CODE REVIEW

**Comment by fat-tire** [comment]
Devs-- If you're waiting for the CLA validation check on this PR not to fail, please see this [issue](https://github.com/signalapp/Signal-Desktop/issues/1034) and [unresolved related discussion](https://whispersystems.discoursehosting.net/t/should-the-contributors-license-agreement-require-personal-info/735) from January '17 regarding privacy concerns w/the CLA.

Best,
ft

PS-- I've now been using Signal on my Chromebook (dev channel) for nearly 3 weeks without encountering any issues.  It works exactly as it would on a phone with all expected features enabled.  Hopefully someone else out there can confirm as well.

**Comment by vangorra** [comment]
@fat-tire You need to fill out the "Contributor License Agreement" before the PR will build or be considered by the project. I also use a chromebook a lot and would love to get this feature in soon.

**Comment by leoluk** [comment]
It won't solve the issue - you would need to use a different phone number.

**Comment by fat-tire** [comment]
@nealey I first [wrote](https://github.com/signalapp/Signal-Desktop/issues/1034) about the CLA issues [2 years ago](https://whispersystems.discoursehosting.net/t/should-the-contributors-license-agreement-require-personal-info/735) without any resolution except to have the issue closed and moved to the forum.  I'm as eager as you to see Signal return officially to Chromebook, but as you can see there's been no response even to this pull request.  So I dunno what to think, but in the meantime you can build for Chromebook yourself, as I am doing w/this PR :)

**Comment by bluefoxicy** [comment]
Well can we work on this somehow?

**Comment by leoluk** [comment]
It's extremely unlikely that the Signal team will change their mind on CLAs, and you can't have both CLAs and privacy (it's a legally binding contract). 

So if anyone wants this to happen, they would have to re-do this PR from scratch and submit it yourself (without looking at the implementation in this PR) or maintain a CLA-less Signal-Android fork.

**Comment by fat-tire** [comment]
@leoluk  Are you speaking with any authority on the Signal team's policy?  I have heard absolutely nothing from them except "put this in the forum", which I did.  What is your basis for your comment?

FWIW, see the reference to pseudoanonymity in US statute (where Signal is based):  [17 USC § 409(2)](https://www.copyright.gov/title17/92chap4.html#408).  Clearly copyright may be assigned/registered to a pseudoanonymous entity given only the nationality/domicile of the author.  I do assert that I'm domiciled in the US.

The question at hand is---  _does or does not the Signal organization value and promote a personal right to privacy, and if so, do these values apply to the developer community as well as the user community?_

More pointedly, is Moxie Marlinspike a "real" name?

> you can't have both CLAs and privacy (it's a legally binding contract).

So EULAs (legally binding supposedly in the US) are unenforcable in cases where both parties aren't identified to each other by name?

**Comment by bluefoxicy** [comment]
> It's extremely unlikely that the Signal team will change their mind on CLAs, and you can't have both CLAs and privacy (it's a legally binding contract).

Just publish your changes under CC-0.

**Comment by fat-tire** [comment]
> Just publish your changes under CC-0.

@bluefoxicy I'm happy to sign the CLA pseudoanonymously or push changes under pretty much any open license they want (including CC0 if that's what's needed.)  The thing is that there has been NO response from any Signal dev that I've seen regarding this  PR.

Which sucks, because I built it again last night from latest source and it works really, really well.  Video conferencing is absolutely amazing on the chromebook-- it opens a second physical window for the call.  Sounds works great.  Video smooth.  And the latest youtube/reddit/imgur "preview" windows seem to work fine too:




Gify stuff is good...



I've had some calls to release a binary, but I'd much rather see it released properly by WS, signed with the correct keys, etc.  Anyone can build & try it themselves tho.  (If you do, you'll probably want to comment out the call to `ApkSignerUtil()` in `build.gradle` and just sign using Android Studio' build+sign feature...)

Please advise, Signal devs!

**Comment by michaelsmoody** [comment]
@fat-tire I'm curious if you've brought the @Trolldemorted branch/PR up to date with current Signal, and if those necessary changes are in yours for making the ChromeOS device a slave device? Or I'll need to merge all of these together? (I haven't looked in depth yet)

**Comment by fat-tire** [comment]
Hey I haven't submitted this to @Trolldemorted if that's what you're asking, but it probably would apply nicely to their repo.  I honestly haven't tried it though.  If you like I could maybe issue a PR there to see what they say?

**Comment by ekovac** [comment]
Is there any chance of reviving this or some similar PR? I'd use Signal a lot more if I could run it on my Chromebook without having to build/run the Electron desktop version in a Linux container.

**Comment by krinara86** [comment]
Any chance of reviving this? My Linux subsystem in chrome os does not support cam and it is a bummer to use it without that.

**Comment by nakedible** [comment]
3 years, still no Chromebook version... any chance this could be revived?

**Comment by fat-tire** [comment]
I could go back to resolve conflicts & try to make it work again, but this PR has been ignored by the Signal people for 3 years now.  I don't think they are interested for some reason.  This really sucks as the electron desktop version on Chromebook is still pretty awful on several fronts and the Android on Chromebook experience is so good.  :sigh:

**Comment by michaelsmoody** [comment]
> I could go back to resolve conflicts & try to make it work again, but this PR has been ignored by the Signal people for 3 years now. I don't think they are interested for some reason. 

Please do. I've made it public several times on Twitter directly to Moxie, and several of the other devs, and to other folks that I know, raising it to several of their actual foundation contributors that real developers are being held back for privacy reasons, and that this is in opposition to their mission. I continue to fight this fight.

**Comment by nakedible** [comment]
I think it was said somewhere at some point that since the project is limited in funding, they have not prioritized this feature. If that is truly the case, then developers: please put a price tag on maintaining this feature, and let's get it funded by donations! Willing to help in that regard. No excuses.

**Comment by fat-tire** [comment]
The thing is, [I don't think they're short on money](https://www.engadget.com/2018-02-22-signal-messenger-50-million-whatsapp-cofounder.html).  If that was the case, they could just say so.  Also, I had already done everything and the commit was just ignored.  This seems to be a case where they just didn't want to do it for some reason.

**Comment by leoluk** [comment]
> This seems to be a case where they just didn't want to do it for some reason.

They probably just ignore every PR without a CLA since they legally can't accept code without a CLA. I'm CTO of an open source company and this matches the advice given to us by our lawyers, which is unfortunate, but that's how the copyright laws work.

**Comment by fat-tire** [comment]
Well, uh I guess I'm looking forward to seeing that when it shows up.   RIP 3+ year-old submission!

**Pull request closed without merging**
