### PR TITLE
Fixes #10820

### LINKED ISSUE #10820: Verify safety number button gets cut out
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
The button to check someone's safety number is cut out a bit in landscape mode

### Steps to reproduce
- open signal
- turn phone to landscape mode
- click on a contact's profile picture 

**Actual result:** verify safety number button gets cut out 

**Expected result:** you should see the whole button or at least be able to scroll up, which you can't

### Device info

**Device:** OnePlus 6t McLaren edition
**Android version:** 10.3.7
**Signal version:** 5.3.5

### Link to debug log (not sure if it helps)

https://debuglogs.org/b47fc1b480bc38c6154bfdfa4ccff871b1fc2407000689a7d92e1e5d7ef0f157

### PR DESCRIPTION
**Pull request by ShivangMahajan**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Honor Play, Android 9
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
 I have added a nested scroll to fix the issue in the landscape mode.

### CODE REVIEW

**Comment by cody-signal** [comment]
Can you fix the merge conflicts and then I'll try to get it merged?

**Comment by ShivangMahajan** [comment]
I have resolved the merge conflicts.

**Comment by cody-signal** [comment]
@ShivangMahajan thanks, looks like this issue occurs in multiple places with out bottom sheets and we'll be doing a more holistic fix for it.

**Comment by ShivangMahajan** [comment]
@cody-signal welcome, okay

**Pull request closed without merging**
