### PR TITLE
fixed typos in polish

### PR DESCRIPTION
**Pull request by m4k5**
### First time contributor checklist

- [ ] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ ] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ ] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [ ] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by FeuRenard** [comment]
Thanks for your interest in contributing to Signal! Translations are not maintained in this git repository. We use the service Transifex to do this. You can apply your changes there: https://www.transifex.com/moxie/signal-android/

**Comment by m4k5** [comment]
Hi @FeuRenard, I have just updated translations on Transifex too, but I am afraid that updating app with them is going to take a long time, as someone submitted fixes of that typos on Trasifex a year ago and they are still not updated :disappointed:

**Comment by RiseT** [comment]
That should be impossible. You can check here when the (polish) strings got pulled from Transifex into GitHub:

https://github.com/signalapp/Signal-Android/commits/master/res/values-pl

**Comment by m4k5** [comment]
Hi @RiseT, you are right - it is a sugestion from philips77 from a year ago. That's because the strings are locked and it is not possible to save changes. I voted for the suggestions and added comments with an issue flag - is there anything more I should do?

https://www.transifex.com/moxie/signal-android/translate/#pl/master/96580360?qt=tygodzie%C5%84
https://www.transifex.com/moxie/signal-android/translate/#pl/master/7548513?qt=lita

**Comment by RiseT** [comment]
@m4k5 Unfortunately, I sort of doubt that voting, commenting or setting issue flags will help (they probably will go unnoticed).

Imho. your best way to go would be contacting an active reviewer or the coordinator of the Polish team via Transifex, so they can unlock the strings in question or use one of the string suggestions. You could do this by using Transifex' private message system or by addressing them directly (like "@username") in the string's comments section:

https://www.transifex.com/moxie/teams/16060/pl/

**Comment by moxie0** [comment]
@RiseT I've added you as a project maintainer on transifex so that you have the ability to resolve issues like this. Thanks!

**Comment by RiseT** [comment]
@moxie0 That's great, thanks!

@m4k5 I've managed to unlock both strings, so you should be able to edit them now.

Note that the first one has substrings for plurals. I've noticed that in addition to your correction noted above, the suggestion you've mentioned by "philips77" uses a translation for the "few" plural form that differs from the currently active one ("tygodni" vs. "tygodnie") . Sadly, I don't know any Polish (well, at least nothing that would help here 😃 ), so your decision.

**Comment by m4k5** [comment]
@RiseT done, I addressed you in my comments. Thanks guys!

**Pull request closed without merging**
