### PR TITLE
Add export chats feature

### PR DESCRIPTION
**Pull request by anlaji**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual Device Nexus One API 24, Android 7.0
 * Virtual Device Pixel 3a API 30_x86, Android 11.0
 * Virtual Device Pixel 3 API 29, Android 10.0
 * Device Samsung Galaxy A3, Android 8.0
- [x] My contribution is fully baked and ready to be merged as is

----------
### Issues
The export function for a single chat was missing.

### Solution
Solution for exporting single conversations from the Android Signal app and saving a package with its content directly into the android device storage.

### Description
Add the possibility to export conversations to a ZIP file including the chat content as an XML file.
Additionally, it is possible to define the desired period of time and whether interchanged files and an HTML-Viewer should be included in the export. The HTML-Viewer enables the user to view the exported data directly.

This function was developed in connection with a bachelor thesis at the Institute for Networks and Security at the Johannes Kepler University Linz.

### Screenshots:
Folie1
Folie2
Folie3
Folie4

### CODE REVIEW

**Comment by garethppls** [comment]
A thought on this. How does the export feature work with disappearing messages? I'll look through the code also but I think this feature needs to work with respect for the fact that the user who sent the message may not want it to be persisted in data.

**Comment by anlaji** [comment]
When disappearing messages are enabled, no message content is stored in the XML file (also no attachments) although theoretically, the export process can have access to the information if it is not already deleted.

**Comment by garethppls** [comment]
Let me give an example. 

> I send you a chat. It is a message that should disappear in 3 minutes. 

> 1 minute after receiving the message you export.

In this example does the disappearing chat get exported? If so we probably should skip the message in the export?

**Comment by anlaji** [comment]
In this example, the message content is not included, but there is information that there was a message just including the author name. I assume that this information also should not be disclosed, so I will remove it. So it complies with the security guideline of Signal.

**Comment by greyson-signal** [comment]
Hi there, I'm sorry, I know you've put a lot of work into this, but we have no plans on integrating any plain-text export of chats. It does look very cool though!

**Comment by UserX404** [comment]
@rmayr 
Please use the [forum](https://community.signalusers.org/t/plain-text-backup-export/4426) for discussion!

**Comment by pazkooda** [comment]
> Hi there, I'm sorry, I know you've put a lot of work into this, but we have no plans on integrating any plain-text export of chats. It does look very cool though!

Hi, I know that you put a lot of work into creating Signal most secure chat app in the world but lack of e.g. export of SMSes to other app (or to any format that can be consumed by non-Signal app) make us - the users that care as privacy as a whole - to have no plans to promote semi-privacy oriented app you create.

Yup, a standard way export your data is true privacy - closed, single app readable is exact opposition of it.

**Pull request closed without merging**
