### PR TITLE
Added a choice between a passphrase and the Android screenlock.

### PR DESCRIPTION
**Pull request by johanw666**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Z3 compact, Android 6.0.1
 * Sony Z1 compact, Android 4.4.4
 * Acer Z205, Android 4.4.2
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

In Settings - Privacy, a setting is added that lets the user switch between a passphrase and Android screenlock for app protection.
screenshot_20180905-085623
or go back to Android system lock:
screenshot_20180905-124057

### CODE REVIEW

**Comment by lichtamberg** [comment]
Please merge this option @moxie0 ❤️ ❤️ ❤️

**Comment by sigenc** [comment]
Yes there are alot of people that want this

**Comment by KarmusDK** [comment]
Adding one more upvote to the pool.

**Comment by leafcutterant** [comment]
@moxie0 merge this, or further prove that Signal has become just another asset of state surveillance.

**Comment by davidcwilliams** [comment]
This! Yes please! On iOS too. Thank you!

**Comment by wheelseal** [comment]
Yes bring it back, Please. There are some Custom ROM wich people can't Acces to Androids-Devise-lock.

**Pull request closed without merging**
