### PR TITLE
Change background connection icon

### LINKED ISSUE #7255: Intrusive & confusing notifications on Android 8.1 without Google Play Services
I have:
- [X] searched open and closed issues for duplicates
- [x] read https://github.com/WhisperSystems/Signal-Android/wiki/Submitting-useful-bug-reports

----------------------------------------

### Bug description
On devices without Google Play Services, Signal creates a notification to inform the user that a background connection has been established to the Signal servers. On earlier versions of Android (pre 8.1), this notification was present but low priority, and therefore did not have an icon in the status bar and did not show up on the lock screen. It only was visible in the expanded notification drawer.

On Android 8.1, however, the background connection notification is visible in both the status bar and the lock screen notification view. Furthermore, it uses the same icon as incoming Signal messages, creating the effect that a message notification is always present and causing user confusion. (See annotated screenshots.)

### Steps to reproduce
- run Signal on a device running Android 8.1 without Google Play Services
- look at the lock screen or status bar

**Actual result:** background connection notification is shown in the status bar and lock screen.
**Expected result:** background connection notification should only be shown in the notification drawer, and the Signal icon should not be present, per previous versions.

### Screenshots
Standard usage of the device, without any dismissable message notifications. (The icon in the status bar is from the background connection notification.)
screenshot_20171207-232132

Standard usage of the device, with an undismissed notification. Note how two Signal icons are present in the status bar, one from the message and the other from the background connection notification.
screenshot_20171207-232226

The expanded notification drawer.
screenshot_20171207-232236

_(Irrelevant sections of screenshots removed for privacy.)_

### Device info
**Device:** Google Pixel
**Android version:** 8.1.0 (without Google Play Services; running CopperheadOS, like raw AOSP)
**Signal version:** 4.13.6

### PR DESCRIPTION
**Pull request by milesmcc**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Google Pixel, Android 8.1 _without Google Play Services_
 * Virtual Google Pixel, Android 8.1 with Google Play Services (not relevant but tested to make sure it worked anyway)
 * Virtual 'Google Pixel', Android 7.0 _without Google Play Services_
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
This pull request changes the icon for the 'background connection enabled' notification to a new icon, `ic_background_connection_dark_24dp` so that it can be differentiated from message notifications in the status bar. Fixes #7255 (though _improves the situation_ is perhaps more accurate).

This is what the expanded notification drawer _used_ to look like (sensitive data removed):
screenshot_20171207-232236

Note how this results in _two_ Signal-icon notifications in the status bar when a message notification is also present:
33751284-dc1cc318-dba7-11e7-9193-91216ddc5194

This pull request changes the background connection icon to `ic_background_connection_dark_24dp` (a new icon created by @ruddfawcett for this purpose), making the message notification icon different from that of the background connection notification, so that the two can be easily differentiated:
screen shot 2018-01-11 at 1 09 17 pm

As for the icon itself, it's supposed to be a cross between a signal coming out of a person—to indicate that the device is connected in the background—and a lock, to go along with the theme of Signal as a _secure messenger_.

This change affects only a small number of users (i.e. users whose phones run Android without Google Play Services), and is only particularly relevant to users of Android >= 8.1 (the background connection notification does not appear in the status bar in lower versions). That is to say, not many will see this icon.

This contribution comes out of a desire to fix something that has been nagging at me ever since I updated to Android 8.1, and I imagine that I'm not the only user who is bothered by the confusing background connection icon. (It looks like I _always_ have a notification.)

I'm happy to change the icon if the chosen one seems inappropriate, though I like the icon.

**This contribution is a freebie.**

(This pull request is an improved version of [this](https://github.com/WhisperSystems/Signal-Android/pull/7275) old pull request. I was asked to change the icon and resubmit.)

### CODE REVIEW

**Comment by p4nci** [comment]
@moxie0 something like this:

signal-background-connection
1) Signal notification icon
2) Signal background connection icon (smartphone communicates with Signal(server))

**Comment by milesmcc** [comment]
Oh wow that's a nice icon @p4nci — if you send the .xml to me I can push it to this PR...

**Comment by p4nci** [comment]
@milesmcc well, unfortunately this is only a mockup, but I'm sure @iadmir (he has worked on the new signal icon) can/will help us 🙏 
btw: here an additional idea: Signal icon with two arrows which represents incoming / outgoing network traffic


35274464-755201ac-003c-11e8-8bfe-bfe7afd8e2f2

**Comment by milesmcc** [comment]
Both of the icons look great @p4nci, but I think icon 3 best maintains Signal's visual identity (doesn't require shrinking the root icon).

**Comment by cernekee** [comment]
https://github.com/signalapp/Signal-Android/issues/7278 suggested using separate notification channels, so that the "background connection" notification could be disabled by the user without affecting other Signal notifications.  I think that would be a cleaner fix.

Current master branch (commit 0bbe83f8f2562) targets API level 25 (not 26) and has no mentions of NotificationChannel.

**Comment by moxie0** [comment]
Some of those mockups look pretty good, please reopen when available

**Comment by p4nci** [comment]
unfortunately @iadmir did not react to my request (pm @community forum), so please can someone provide the original SVG Signal icon?

Making a vector graphic from a png file it does NOT work as expected, at least for me 😞

**Comment by michaelkirk-signal** [comment]
@p4nci is anything here helpful to you? 

https://github.com/signalapp/Signal-Design/tree/master/android/icons/app_icon

**Comment by p4nci** [comment]
@michaelkirk-signal yes, thanks. Somehow I missed this one :rage:

**Comment by milesmcc** [comment]
@p4nci I'm happy to change my original PR branch to use your new icon, FYI—I want to get this pushed through ASAP!

**Comment by p4nci** [comment]
update:
sorry guys but I have "saturday day(night) fever" :face_with_thermometer: 
please be patient with me.
btw. the very good news from @iadmir that he will look into it.

**Comment by iadmir** [comment]
@p4nci thanks for the mention, I received the first notification but I forgot about this.

dark
16x16px - https://user-images.githubusercontent.com/23726384/37241571-9857f5a6-245b-11e8-93b6-01fdb48df6b9.png
24x24px - https://user-images.githubusercontent.com/23726384/37241572-98802224-245b-11e8-830d-d83f1b710d59.png)
36x36px - https://user-images.githubusercontent.com/23726384/37241573-98a143be-245b-11e8-8bd0-883a851176f4.png)
48x48px - https://user-images.githubusercontent.com/23726384/37241574-98c2d470-245b-11e8-8b31-040f57b5ceb4.png)
72x72px - https://user-images.githubusercontent.com/23726384/37241575-98e472ce-245b-11e8-8393-ac9252bc148d.png)
100x100px - https://user-images.githubusercontent.com/23726384/37241576-990e0026-245b-11e8-8982-7de4473fd5d4.png)

**Comment by milesmcc** [comment]
@iadmir would it be possible to convert that to a SVG? That way we could simply add it as an icon asset and go from there.

**Comment by iadmir** [comment]
Sure, there is compressed svg.
[icon-signal.svg.zip](https://github.com/signalapp/Signal-Android/files/1800244/icon-signal.svg.zip)

**Comment by p4nci** [comment]
@iadmir just one thing, it's the wrong signal icon (the "symmetric" one, see also https://github.com/signalapp/Signal-Android/issues/5936#issuecomment-272856245)

btw. still :face_with_thermometer:

**Comment by iadmir** [comment]
Oh you're right, good observation, I edited the previous comment with attached svg

**Comment by p4nci** [comment]
@milesmcc the svg-icon provided by @iadmir should be sufficient? 🤔

**Comment by milesmcc** [comment]
@p4nci it is sufficient, but requires converting into an Android-ready `.xml` icon. I've been hacking on it in my spare time, but haven't yet found a non-hacky way to convert it into a form that the Signal maintainers would comfortably accept. @iadmir — would it be possible for you to export the icon as a `.xml` icon from your image editor?

**Comment by iadmir** [comment]
I use Ai for vector design and there isn't option to save as .xml but I think Adobe InDesign can export this format.

**Comment by p4nci** [comment]
this:
[android-working-with-vectordrawable-can-we-easily-convert-svg-to-vectordrawable](https://medium.com/@nandankaushik/android-working-with-vectordrawable-can-we-easily-convert-svg-to-vectordrawable-e4000143b13f)
might be helpful

one more thing:
the svg-icon has a background (with color #808080). Do we really need a background for this icon? AFAIK the icon should/must be transparent.

**Comment by nikwen** [comment]
When I need to convert svg icons to VectorDrawables, I use this tool: https://inloop.github.io/svg2android/

The conversion yields:

```
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="500dp"
    android:height="500dp"
    android:viewportWidth="500"
    android:viewportHeight="500">

    <path
        android:fillColor="#808080"
        android:pathData="M -0.5 -0.5 H 499.5 V 499.5 H -0.5 V -0.5 Z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M362.8,246h-49.3c-10.7,0-19.5,8.8-19.5,19.5v62.8v12.1v23.7c0,10.7,8.8,19.5,19.5,19.5h49.3 c10.7,0,19.5-8.8,19.5-19.5v-98.6C382.3,254.8,373.5,246,362.8,246z M351.1,369.8h-26v-7.2h26V369.8z M370.9,348.7h-65.6v-9.3 v-12.3v-59.2h65.6V348.7z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M210.1,261.9c-6.1,0-12.2-0.7-18.1-2.2c-0.8-0.2-1.5,0-2.2,0.4c-7.1,4.1-14.2,8.3-21.4,12.4 c-1.4,0.8-2.5,0.8-3.3-0.1c-0.5-0.5-0.7-1.1-0.7-1.8c-0.6-7.3-1.2-14.7-1.7-22c0-0.6-0.2-0.9-0.7-1.3 c-11.6-9.1-18.5-21.1-21.5-35.4c-2.9-13.5-2.2-26.8,3.4-39.6c6.4-14.5,16.8-25.3,30.7-32.7c10.6-5.7,22.1-8.5,34.1-8.7 c18.1-0.2,34.5,5,48.6,16.5c13,10.6,21.2,24.1,23.5,40.9c2.3,17.2-2.2,32.8-12.9,46.4c-11.6,14.7-27,23.2-45.4,26.3 c-1.6,0.3-3.1,0.5-4.7,0.6C215.2,261.8,212.6,261.9,210.1,261.9z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M300.4,200.1c-0.3,5.9-1.2,11.6-2.7,17.3c-0.3,1-0.7,1.2-1.6,0.8c-1-0.4-2.5-0.4-3-1.1 c-0.6-0.8,0.3-2.1,0.6-3.1c1.2-5.2,2-10.5,2.1-15.9c0-0.8,0.3-1.1,1.1-1.1c0.9,0.1,1.8,0.1,2.8,0c0.8,0,1,0.3,1,1.1 C300.5,198.8,300.5,199.4,300.4,200.1z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M210.3,111.4c2.3-0.1,4.9,0.1,7.5,0.3c0.8,0,1.2,0.3,1,1.2c-0.2,0.9-0.2,1.8-0.3,2.6c0,0.8-0.4,0.9-1.1,0.9 c-6.2-0.6-12.3-0.4-18.5,0.3c-0.9,0.1-1.1-0.1-1.2-0.9c0-0.9-0.2-1.8-0.4-2.6c-0.1-0.7,0.1-1.1,0.9-1.1 C202.2,111.7,206.1,111.3,210.3,111.4z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M210,280.9c-1.7,0-3.4,0-5.1,0c-0.7,0-0.9-0.2-0.9-0.9c0.1-0.9,0.1-1.8,0.1-2.7c-0.1-1.1,0.4-1.3,1.4-1.2 c2.8,0.2,5.7,0.1,8.5,0c3.1-0.1,6.3-0.4,9.4-0.9c1.1-0.2,1.7,0,1.7,1.3c0,0.8,0.2,1.5,0.4,2.3c0.2,0.8,0,1-0.8,1.1 C219.8,280.5,214.9,280.9,210,280.9z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M296.5,188.8c-0.8,0.3-1.1-0.2-1.2-1.2c-0.6-6-2-11.9-4.1-17.5c-0.3-0.9-0.2-1.2,0.7-1.5 c0.8-0.3,1.7-0.6,2.5-0.9c0.7-0.3,1-0.1,1.2,0.6c1.6,4.4,2.9,8.9,3.7,13.6c0.3,1.9,0.5,3.7,0.8,5.6c0.1,0.8-0.1,1.2-0.9,1.2 C298.3,188.6,297.5,188.7,296.5,188.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M122.1,200.8c2.3,0,2.3,0,2.4,2.3c0.3,5.8,1,11.5,2.3,17.2c0.2,0.6,0.1,1-0.6,1.1c-1,0.2-2,0.4-2.9,0.7 c-0.7,0.2-1,0-1.1-0.7c-0.9-3.9-1.5-7.8-1.9-11.7c-0.3-2.6-0.4-5.1-0.5-7.7c0-0.9,0.2-1.2,1.1-1.1 C121.2,200.9,121.6,200.8,122.1,200.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M189.8,117.8c0.1,0.6-0.3,0.6-0.6,0.7c-6.2,1.4-12.2,3.5-17.9,6.3c-0.5,0.3-0.8,0.1-1-0.4 c-0.5-1-0.9-1.9-1.4-2.9c-0.3-0.5-0.1-0.8,0.4-1c6.1-2.9,12.3-5.1,18.9-6.6c0.3-0.1,0.8-0.2,0.9,0.3 C189.3,115.4,189.6,116.7,189.8,117.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M139.2,246.3c0,0.3-0.3,0.5-0.5,0.6c-0.8,0.6-1.6,1.2-2.3,1.9c-0.6,0.6-1,0.4-1.5-0.2 c-3.6-4.4-6.5-9.3-8.7-14.5c-0.4-0.9-0.8-1.9-1.2-2.9c-0.3-0.6-0.2-0.9,0.5-1.1c0.9-0.3,1.9-0.6,2.8-1c0.7-0.3,1-0.2,1.3,0.6 c1.5,4,3.4,7.7,5.7,11.2c1,1.6,2.1,3.1,3.3,4.6C138.9,245.8,139,246.1,139.2,246.3z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M234.5,277.8c-0.6,0.1-0.7-0.3-0.8-0.6c-0.2-1-0.5-1.9-0.8-2.9c-0.2-0.7-0.1-1,0.7-1.3 c6.1-1.6,11.9-3.8,17.5-6.7c0.5-0.2,0.8-0.3,1,0.3c0.5,1,1,2,1.5,2.9c0.3,0.5,0.2,0.8-0.3,1c-6,3-12.2,5.4-18.7,7.2 C234.6,277.7,234.5,277.8,234.5,277.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M279.4,141.8c0.2,0.2,0.4,0.3,0.5,0.5c4.5,5,8.2,10.5,11.4,16.5c0.3,0.6,0.2,0.9-0.4,1.2 c-0.9,0.4-1.7,0.8-2.6,1.3c-0.6,0.3-1,0.3-1.3-0.4c-2.9-5.6-6.5-10.7-10.6-15.4c-0.5-0.5-0.4-0.8,0.1-1.2c0.8-0.6,1.5-1.3,2.2-2 C278.9,142.1,279.2,141.9,279.4,141.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M294.3,227c-0.1,0.2-0.1,0.4-0.2,0.6c-2.6,6-5.9,11.7-9.7,17c-0.5,0.7-0.9,0.8-1.5,0.2 c-0.7-0.6-1.4-1.1-2.1-1.6c-0.7-0.4-0.7-0.8-0.2-1.5c3.4-4.6,6.3-9.4,8.7-14.7c1-2.2,1-2.2,3.3-1.3c0.5,0.2,1,0.4,1.4,0.6 C294.1,226.5,294.4,226.6,294.3,227z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M122.1,192.5c-2.5-0.2-2.5-0.2-2.3-2.7c0.5-6.1,1.6-12,3.5-17.8c0.2-0.8,0.5-1,1.3-0.7 c0.8,0.3,1.7,0.6,2.5,0.8c0.8,0.2,1,0.5,0.7,1.3c-1.2,3.6-2,7.3-2.6,11.1c-0.3,2.2-0.6,4.4-0.7,6.6c0,1.1-0.4,1.5-1.5,1.3 C122.7,192.5,122.4,192.5,122.1,192.5z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M228,113c4.6,0.9,9.1,2.1,13.5,3.6c1.9,0.7,3.8,1.5,5.7,2.2c0.7,0.2,0.9,0.6,0.5,1.2 c-0.4,0.9-0.8,1.7-1.2,2.6c-0.2,0.6-0.5,0.8-1.2,0.5c-5.8-2.5-11.8-4.3-18-5.5c-0.6-0.1-0.8-0.4-0.7-1c0.2-1.1,0.4-2.1,0.6-3.2 C227.4,113.1,227.5,112.9,228,113z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M130.6,164.8c-1.1-0.5-2.4-1.1-3.6-1.7c-0.4-0.2-0.1-0.5,0-0.8c2.8-6.1,6.4-11.8,10.6-17.1 c0.4-0.5,0.6-0.5,1.1-0.1c0.8,0.7,1.6,1.4,2.5,2c0.4,0.3,0.5,0.6,0.1,1.1c-4,4.9-7.3,10.3-10,16.1 C131.3,164.5,131.2,164.8,130.6,164.8z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M196.3,275.7c0,0.1,0,0.1-0.1,0.2c-0.3,1.2-0.2,2.8-1,3.4c-0.9,0.8-2.3-0.3-3.4-0.5c-0.5-0.1-0.9,0-1.4,0.2 c-4.1,1.8-8.1,3.5-12.2,5.3c-0.8,0.4-1.3,0.3-1.6-0.6c-0.3-0.9-0.7-1.7-1.1-2.5c-0.3-0.6-0.1-0.9,0.5-1.2c4.6-2,9.3-4,13.9-6 c0.6-0.3,1.3-0.3,1.9-0.1c1.2,0.3,2.4,0.7,3.6,1C196.1,275,196.4,275.1,196.3,275.7z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M155,270.5c0.1,0.5-0.1,0.7-0.4,0.8c-1.1,0.3-2.2,0.7-3.3,1.1c-0.8,0.2-0.8-0.3-1-0.8 c-1.1-3.4-2.2-6.8-3.3-10.2c-0.3-1.1-0.8-1.9-1.7-2.6c-1.1-0.8-2-1.7-3.1-2.5c-0.5-0.4-0.5-0.7,0-1.1c0.8-0.8,1.5-1.6,2.2-2.5 c0.3-0.3,0.5-0.4,0.9-0.1c1.6,1.3,3.1,2.6,4.7,3.9c0.4,0.3,0.7,0.8,0.8,1.3c1.3,4.2,2.7,8.4,4,12.5 C155,270.4,155,270.6,155,270.5z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M273.2,135.6c-0.1,0.1-0.1,0.2-0.2,0.3c-0.8,0.9-1.6,1.7-2.4,2.6c-0.5,0.6-0.8,0.1-1.2-0.2 c-2.7-2.5-5.7-4.7-8.7-6.8c-2-1.4-4.1-2.7-6.3-3.9c-0.8-0.4-0.9-0.8-0.4-1.5c0.5-0.8,0.9-1.6,1.3-2.4c0.3-0.6,0.6-0.7,1.2-0.3 c5.8,3.3,11.2,7.1,16.2,11.6C272.9,135.2,273.2,135.3,273.2,135.6z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M278,251.9c0,0.3-0.3,0.5-0.4,0.7c-4.6,4.9-9.8,9.1-15.3,12.8c-0.6,0.4-0.9,0.3-1.2-0.3 c-0.5-0.8-0.9-1.5-1.5-2.2c-0.6-0.8-0.5-1.2,0.3-1.7c3.9-2.5,7.5-5.5,10.9-8.6c1.1-1,2.2-2.1,3.2-3.2c0.5-0.5,0.8-0.5,1.3,0 c0.8,0.8,1.5,1.5,2.3,2.2C277.8,251.6,277.9,251.8,278,251.9z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M158.8,292.6c-1.1-0.1-1.9-0.6-2.3-1.6c-1.1-3.2-2.1-6.4-3.1-9.6c-0.2-0.5,0-0.7,0.5-0.9 c1-0.3,2.1-0.6,3.1-1c0.6-0.2,0.9,0,1.1,0.6c0.6,2,1.3,3.9,1.9,5.9c0.2,0.7,0.5,0.9,1.2,0.5c1.8-0.9,3.7-1.6,5.6-2.5 c0.7-0.3,1.1-0.2,1.3,0.5c0.4,1,0.8,1.9,1.2,2.8c0.2,0.4,0.2,0.7-0.3,0.9c-3.2,1.4-6.3,2.7-9.5,4.1 C159.3,292.5,159,292.6,158.8,292.6z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M147.2,141.5c-0.1-0.1-0.3-0.3-0.5-0.4c-0.6-0.6-1.2-1.3-1.9-1.9c-0.8-0.6-0.8-1.1,0-1.8 c4.4-4.2,9.2-8,14.3-11.3c1.8-1.2,1.8-1.2,2.9,0.6c1.4,2.2,1.4,2.2-0.8,3.6c-4.8,3.1-9.2,6.6-13.2,10.5 C147.8,141.1,147.6,141.4,147.2,141.5z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M256,310.4c-7.7-8.1-12.3-17.5-13.3-29.2c-3.8,1.3-7.2,2.3-11.2,3.1c1.6,13.5,6.7,24.7,15.9,34.3 c10.7,11.2,25,17.7,41.1,17.9v-12C275.6,324.4,264.3,319.2,256,310.4z" />
    <path
        android:fillColor="#FFFFFF"
        android:pathData="M379.3,246.5c-1.2-14.1-6.6-27.3-16.5-37.7c-14.7-15.4-35-21.4-56.5-18.2c0.1,1.8,0.2,3.6,0.2,5.4 c0,2.3-0.1,4.5-0.3,6.8c3.7-0.7,6.5-1,10.1-1c14.4,0,28,5.1,37.8,15.4c6.2,6.5,10.2,14.5,12.2,23 C371.4,240.4,376,242.9,379.3,246.5z" />
</vector>
```

**Comment by nikwen** [comment]
The background color should of course be removed. :wink:

**Comment by p4nci** [comment]
> svg2android

@nikwen jep, see my comment above (in the link that I posted svg2android is mentioned as "the best solution").

@milesmcc the first path is the background, so you can delete it:
```
     <path
        android:fillColor="#808080"
        android:pathData="M -0.5 -0.5 H 499.5 V 499.5 H -0.5 V -0.5 Z" />
```

**Comment by milesmcc** [comment]
@p4nci here's the current problem with the PR: the icon needs to be scaled within its squared window so that it is the proper size for a notification. (Right now, it takes up about 75% of the window.)

@iadmir — would it be possible for you to make a small edit of your original icon (which is _awesome_) so that it uses 100% of the height of the SVG window? I tried to fiddle with it myself, but don't have the necessary SVG knowledge.

Thanks!

**Comment by nikwen** [comment]
@milesmcc Try this. [icon-signal-2-modified-nikwen.zip](https://github.com/signalapp/Signal-Android/files/1988916/icon-signal-2-modified-nikwen.zip)
By the way, thanks for giving an update. :+1:

**Comment by nikwen** [comment]
@milesmcc Sent you a PR: https://github.com/milesmcc/Signal-Android/pull/1

**Comment by nikwen** [comment]
Thank *you*, @milesmcc. :)

**Comment by milesmcc** [comment]
@p4nci, @cernekee, @michaelkirk-signal, @iadmir, and @nikwen: see #7787. Thanks for all your help and feedback!

**Comment by greyson-signal** [comment]
Hi there! Just merged a new icon for this into 4.30. Special thanks to @p4nci who reached out and sent the icon design. Thanks, everyone!

**Pull request closed without merging**
