### PR TITLE
Fixes #8058 makes sure pasted text doesn't have formatting

### LINKED ISSUE #8058: UI: Rich Text Can be Pasted into a Signal Message
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Pasting rich text, such as HTML markup from a website into a Signal message will carry over the text's original formatting. In some cases, it looks silly, and in others, such as with enormous text, it makes the text field unusable (or at least undesirable)

Since Signal can't send texts of different sizes, colors, boldness, etc. we should sanitize text that gets pasted into the app. 

I would like to note that actually sending the message will strip the formatting and not cause any actual problems. This mostly just looks confusing to users and could potentially be very confusing depending on the nature of the formatted text pasted into Signal. 

### Steps to reproduce
- Navigate to a site with rich text, such as this one https://www.marxists.org/reference/archive/debord/society.htm
- Copy and paste some text. I chose: 

> 1.
> In societies where modern conditions of production prevail, all of life presents itself as an immense accumulation of spectacles

 since the "1." in that quote is formatted with the `<h5>` HTML element. 
- Open Signal and paste the text into a message.

**Actual result:** The external markup has found its way into Signal! 
**Expected result:** The markup should be stripped from the selected text as if the user were to have just typed the pasted quote by hand.

### Screenshots
Here's a screenshot of Signal after following the steps outlined above
image
As you can see, the formatting, size, and alignment of the "1."'s `<h5>` element is preserved 

### Device info
**Device:** Alcatel_5044R
**Android version:** 7.0
**Signal version:** 4.24.5

### PR DESCRIPTION
**Pull request by bitmold**
### First time contributor checklist

- [ ] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ ] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

### CODE REVIEW

**Comment by cody-signal** [comment]
This will break pasting mentions which is a spannable. Please revise.

**Comment by bitmold** [comment]
Ok sure, I'm on the road right now and won't be on a computer til next week or so. I can take a look at it then

**Comment by darkdragon-001** [comment]
Any news here?

**Comment by darkdragon-001** [comment]
@cody-signal might be helpful to point @bitmold to the method detecting the mentions markup before sending a message.

**Pull request closed without merging**
