### PR TITLE
Fix Meteor0id enhance ringing sounds

### PR DESCRIPTION
**Pull request by Sgn-32**
### Contributor checklist

- [X] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [X] I have tested my contribution on these devices:
 * Moto X Play, Android 7.1.1

- [X] My contribution is fully baked and ready to be merged as is
----------

### Description

PR with @Meteor0id improved sound files for outgoing and busy calling sound.
Learn more: https://github.com/signalapp/Signal-Android/pull/8948

### CODE REVIEW

**Comment by Meteor0id** [comment]
There are also two other files which could potentially be added to this PR but those would require some code changes:
1. a sound for the connecting / establishing phase of a call. This one sounds very similar to outing, with only a minor difference in the time between each ring sound. The goal is to make the difference between connecting and actually calling audible to people who cannot easily read their screen (accessibility).
2. A call ended sound. Don't you just hate when someone hangs up and you have to check your screen to make sure the call actually ended? It's just a single low tone beep.

Would be nice to add those too but if you end up just merging outgoing and busty sounds that's still a nice enhancement.

**Comment by Sgn-32** [comment]
`This issue has been automatically marked as stale...`

This isn't an issue, it's a PR.
I hope design prefers a clear ringtone and not noisy ones.

**Comment by clauz9** [comment]
ha ha... The bot got his wires crossed 🤣

**Comment by Sgn-32** [comment]
Still no news from Design?
Since it's Christmas, I hope Design gets a good music system as a gift.
So they no longer need to use a gramophone for sound tests.

**Review by dev-aniketj — APPROVED** [review]

**Comment by UnderscoreX5** [comment]
We seem to be getting a calls overhaul but the sound hasn't been touched upon yet.. I really hope they work on it since it's a stupidly simple task compared to all the awesome work they've done for calls in the current beta.

**Comment by Sgn-32** [comment]
Seen this feature request in the forum:

https://community.signalusers.org/t/the-dialing-sounds-are-not-the-same-between-android-and-desktop-versions/53153

How about the ringing sound of Signal Desktop?

https://github.com/signalapp/Signal-Desktop/blob/main/sounds/ringtone_minimal.ogg

Or sounds from Signal iOS?

https://github.com/signalapp/Signal-iOS/blob/main/Signal/AudioFiles/ringback_tone_ansi.caf
https://github.com/signalapp/Signal-iOS/blob/main/Signal/AudioFiles/busy_tone_ansi.caf

**Comment by Meteor0id** [comment]
Such a simple fix, lets not waste it by ignoring it

**Comment by Sgn-32** [comment]
A comment for stalebot

**Comment by Meteor0id** [comment]
.

**Comment by Meteor0id** [comment]
Kick

**Comment by Meteor0id** [comment]
Signals noicy ribgtones still hurt my ears. I love the authentic old sound but the noice shouldn't be part if it

**Comment by Sgn-32** [comment]
Why not test it in the next beta and get feedback from the beta testers?

**Comment by Sgn-32** [comment]
Oh no, stale-bot.

**Comment by cody-signal** [comment]
For anyone curious, this is still true:

> I've brought this up to design multiple times, it's in their court.

**Comment by Sgn-32** [comment]
Stale-bot! Why closed?
A dev has commented after marking as "wontfix".
Shouldn't comments from devs remove the "wontfix"-label?

**Pull request closed without merging**
