### PR TITLE
Add disappearing message time of 10 minutes

### LINKED ISSUE #6013: Feature Request: Disappearing Message Time of 15 Minutes
The disappearing message function is something that I make heavy use of, but there seems to be a gap in the options.
When thinking about how long some conversations go, 5 minutes seems too quick, but 30 minutes is too long.
I'd love for there to be a 15 minute option.

Given some of the feature requests I saw while looking to see if someone else asked for 15 minutes, it might be smart to support a custom time option somewhere.

### PR DESCRIPTION
**Pull request by merge**
This adds 10 minutes to the selectable times for disappearing messages,
making the minutes' values match the seconds'.

Fixes #6013

### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor Licence Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Virtual device Nexus 5, Android 6.0
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)
- [x] I have made the choice whether I want the [BitHub reward](https://github.com/WhisperSystems/Signal-Android/wiki/BitHub-Rewards) or not by omitting or adding the word `FREEBIE` in the commit message of my first commit

----------

### Description

This simply adds 10 minutes to the list for disappearing messages, making the list feel more complete.

### CODE REVIEW

**Comment by moxie0** [comment]
I feel like this is a bike shed waiting to happen, and I'm mostly satisfied with the current values. If we want to change it, we'd have to change it in all three clients.

**Comment by scienmind** [comment]
Some people want 5 minutes, some 15, some 10...

I think best way would be to make the number editable / add "custom delay" :
as in: you'd still be scroll up/down to choose preset value, but if you tap the "selected" time value, you'll be able to edit it (using keyboard or whatever). This would "blanket cover" all the requests.

I won't consider it strictly "adding more options, hence against OWS policy"  - we already have several "timeout options" it'd just make one of them customizable.

**Comment by merge** [comment]
bike shed, maybe yes, but I don't think so. this just makes the list feel more complete and could reduce discussions around this.

In practice, I don't think people really would type in a custom delay. I don't see people taking the effort actually. I at least can't imagine that this would be worth it.

It's all really not too important and equally fine would be moxie just making any decision and ignoring this topic altogether :)

**Comment by merge** [comment]
After 4 months: 6 thumbs up, 4 thumbs down. Signal-Desktop only closed it because they tidied up their PR list and wait for your decision. It would be ready for iOS, Desktop and Android.

If you'd make a decision, I could tidy up my repository list too :) thanks

**Pull request closed without merging**
