### PR TITLE
Do not move archived to top of conversation list on new message

### PR DESCRIPTION
**Pull request by garethppls**
### First time contributor checklist

- [x] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nokia 4.2, Android 11
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description
**Feature request: Do not move archived messages to top of conversation list on new message**
Thread on this feature request: https://community.signalusers.org/t/do-not-un-archive-muted-conversations/6165/27

This is implemented with a toggle in the Chat settings page.
When the toggle is enabled an archived chat will not pop to the top of the conversation list:
Screenshot_20211214-193026

This is my first PR, if there's anything I've neglected to do please say and I'll be willing to make some changes if necessary.

Thank you!

### CODE REVIEW

**Comment by kiplingw** [comment]
Thanks a lot, @garethppls. Hopefully this gets merged.

**Comment by garethppls** [comment]
Thanks for this @kiplingw. The reason why I didn't do this is because I didn't want to overcomplicated this change.
I consider whether a message is archived, and whether notifications are on to be separate. I move a message to archived because I want it out of the way. I mute a chat because I don't want to have notifications.

**Comment by Tomptez** [comment]
Thanks for this PR, I hope it'll get merged soon. I've been waiting for this forever!

**Comment by clauz9** [comment]
Use rebase to update the PR branch instead of merge.

**Comment by clauz9** [comment]
cool 👍  now resolve the conflicts

**Comment by garethppls** [comment]
@clauz9 - Done - thanks.

**Comment by njmulsqb** [comment]
Hi @garethppls ,

Thanks a lot for working on this feature. Do you have any idea when this PR will get merged? Any contact with the internal team of signal? Its much needed feature

**Comment by Meteor0id** [comment]
I would also include another change: move the button to open the archive to the top of the chats. Pinned chats still go above the button though. That makes it much easier to reach the archive when you have a lot of chats. And add an indicator on the button to open the archive to indicate that there are new messages in an archived chat. These changes are similar to what WhatsApp did and WhatsApp did well on this.

**Comment by garethppls** [comment]
> Hi @garethppls ,
> 
> Thanks a lot for working on this feature. Do you have any idea when this PR will get merged? Any contact with the internal team of signal? Its much needed feature

No reply from the Signal team. I'd like to get this merged, and I'd love to contribute.

**Comment by garethppls** [comment]
> I would also include another change: move the button to open the archive to the top of the chats. Pinned chats still go above the button though. That makes it much easier to reach the archive when you have a lot of chats. And add an indicator on the button to open the archive to indicate that there are new messages in an archived chat. These changes are similar to what WhatsApp did and WhatsApp did well on this.

Nice idea. I think this could be something to explore _after_ I get this PR closed out as a separate change. I think it would be too controversial to add to this change.

**Comment by Tomptez** [comment]
@greyson-signal I really fail to understand your decision on this. This is by far the most aggravating behavior of signal, especially if you are in a bunch of group-chats that don't require your regular participation but clutter your entire inbox so that you easily overlook new messages in actually relevant conversations. To me, this is really a must have feature for anyone that is part of many group chats and I know countless people using this feature in telegram regularly. I am perfectly happy with this being a opt-in feature only for those who actually feel like they need it but I strongly urge you to reconsider your decision on this.

**Comment by Meteor0id** [comment]
The real issue has nothing to do with archiving. I think what we really need is something between muting and blocking: some option to prevent bumping chats up. https://community.signalusers.org/t/option-to-not-bumb-muted-chats-up-in-conversation-list-supermute-or-light-blocking/44246

**Comment by lucasriondel** [comment]
This is indeed much needed. And since it's a toggle in the settings, and it has already been developed by @garethppls (thanks a lot), I do not get why this is not merged too. Please reconsider !

**Comment by kennu** [comment]
+1 for this. It's very annoying that you can't make archived chats stay archived like in WhatsApp. Would be a simple checkbox setting.

**Comment by greyson-signal** [comment]
You can go to Settings > Chats and toggle "Keep muted chats archived". That should get you most of what you want.

**Comment by greyson-signal** [comment]
Ah it might only be enabled internally, my bad. But we should be able to enable this externally soon (it's one of those things where we have to wait to make sure linked devices  support syncing the setting and stuff). Should be soon!

**Comment by kennu** [comment]
That sounds great, thanks.  Will let me keep chats a bit more organized.

**Comment by Tomptez** [comment]
That would be fantastic. Can't wait!

**Comment by Penguinjumper** [comment]
for now, is it possible to enable this without any GUI implementation? Like, is there a config file for Signal Android or Desktop?

> Ah it might only be enabled internally, my bad. But we should be able to enable this externally soon (it's one of those things where we have to wait to make sure linked devices support syncing the setting and stuff). Should be soon!

**Comment by nicholas-signal** [comment]
> for now, is it possible to enable this without any GUI implementation? Like, is there a config file for Signal Android or Desktop?

This feature is now public, and is called "Keep Muted Chats Archived" and can be enabled on your primary device.

**Comment by Penguinjumper** [comment]
Wow haha that is so awesome! Just when I really needed it :) 
Wonder if the desktop versions will stick to this if toggled on the primary device!

**Comment by nicholas-signal** [comment]
> Not working on Desktop as of now (Mac M1, 6.3.0).

Can you describe this more? And submit a debug log? Linked devices should respect this setting.

>  do you know if there will be any indicator for new messages in archived chats?

If that is something that you would like, I encourage you to submit it as a Feature Request on our community forum: https://community.signalusers.org/c/feature-requests/17

**Comment by kennu** [comment]
I think that if you write to yourself with "Note to Self" muted, the chat still gets unarchived even with "Keep Muted Chats Archived" enabled. I tried it between Windows Desktop 6.3.0 and Android. Didn't get any messages in other chats right now..

**Comment by nicholas-signal** [comment]
> I think that if you write to yourself with "Note to Self" muted, the chat still gets unarchived even with "Keep Muted Chats Archived" enabled. I tried it between Windows Desktop 6.3.0 and Android. Didn't get any messages in other chats right now..

This is intended behavior: sending a message to a chat will always unarchive it.

**Pull request closed without merging**
