### PR TITLE
Added a choice between Google Map types

### PR DESCRIPTION
**Pull request by johanw666**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Sony Z3 Compact, Android 6.0.1
 * Sony M4 Aqua Android 5.0

- [x] My contribution is fully baked and ready to be merged as is
----------

### Description

Signal-maptype

Screenshot_20200322-125505

### CODE REVIEW

**Comment by Meteor0id** [comment]
As a viewer of a location which was shared to me, I would like to be able to toggle back and forth between satellite and roadmap while viewing the map. I do this often, it often really helps find the right location much faster. A setting under options would not allow me to toggle back and forth. Which map type I want to see depends on the location and circumstances, so that should not be a global setting.

**Comment by johanw666** [comment]
> As a viewer of a location which was shared to me, I would like to be able to toggle back and forth between satellite and roadmap while viewing the map.

Something with toggle buttons on the selection screen? Like this:

Screenshot_20200329-011026

**Comment by johanw666** [comment]
I've aded 3 type selection buttons to the place picker (more looks cramped IMO). They also change the setting so the change is persistent.
Screenshot_20200331-160554

**Comment by halb9** [comment]
Would it be possible to have the layer symbol just like in the google maps app (top right corner)? 

eff01
eff02

**Comment by johanw666** [comment]
> Would it be possible to have the layer symbol just like in the google maps app (top right corner)?

That could be done but you are asking for much more: not only a selectable map type, but only a layer selector like Google Maps has. The advantage of this solution is that quick switching is possible.

**Comment by Meteor0id** [comment]
A choice between layers is still missing in Signal

**Comment by Meteor0id** [comment]
Still missing

**Comment by greyson-signal** [comment]
Hi, thanks for the time ya'll spent on this, but I don't think this is how we'll be doing this.

**Comment by Meteor0id** [comment]
Hope there will be some viewing choices for maps in the future. Sometimes a satelite view is very useful.

**Pull request closed without merging**
