### PR TITLE
Share multiple photos/files

### PR DESCRIPTION
**Pull request by gabrielsimoes**
### First time contributor checklist

- [x] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)
- [x] I have read [how to contribute](https://github.com/WhisperSystems/Signal-Android/blob/master/CONTRIBUTING.md) to this project

### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/WhisperSystems/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Nextbit Robin, Lineage OS 14.1 (Android 7.1.2)
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

As of issue #2159. Supports sharing multiple images/files from the select dialog, from the quick attachment menu, and by sharing multiple files from other app.

### CODE REVIEW

**Comment by gabrielsimoes** [comment]
Alright, I have finished implementing it. I still have to add the commit message closing issue #2159 though. I'll squash the commits and do it as soon as a maintainer says it is ready to be merged.

**Comment by Sakarisson** [comment]
Any news on when this will be merged to master?

**Comment by gabrielsimoes** [comment]
I'll try to solve the conflicts by tonight.

**Comment by gabrielsimoes** [comment]
Alright, conflicts resolved.

**Comment by gabrielsimoes** [comment]
This PR has been sitting for almost two months without any response. Could you guys from Signal at least give us an of when it is going  to be reviewed/merged or why this hasn't happened before. It is not like the project is dying, you know. Just a few weeks before a developer from Signal committed similar changes to the same file I did (eg: displaying pictures in their real size)

**Comment by piratenpanda** [comment]
I don't know but other users like greyson request reviews in their PRs. Maybe you can do the same?

**Comment by kaslusimoes** [comment]
Bump

**Comment by greyson-signal** [comment]
Hi @gabrielsimoes! Thank you so much for taking the time to implement this. Unfortunately, we can't merge this PR in its current form, and we plan on taking a different approach when we add this feature.

Enabling support for multiple attachments is something we've been thinking about, and we know that this is a feature that our users want. However, we need to have a coordinated implementation in all of the Signal clients in order for this type of feature to work well across millions of users.

For performance and efficiency reasons, the approach that is implemented here (sending a separate message for each attachment) is not how we anticipate doing this.

The necessity of coordinating features across platforms is why we recommend starting out by submitting small PRs in our [Contributing Guidelines](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md). Reviewing larger changes also takes more time, especially as we have been working on other frequently requested features.

I know this is likely frustrating, but I hope you continue to be involved in the community in the future. There is some nice code here, and you have clearly developed a familiarity with the codebase that will be helpful as we all continue to make improvements to Signal. Thanks!

**Comment by gabrielsimoes** [comment]
Hi @greyson-signal. Frustating is understatement. I'm pretty aware this solution is not the most efficient. I began this PR simply as a scratch I could later improve using the feedback I would receive from you guys. It wasn't a closed feature, and I really don't think it should have been closed as such. Had you replied earlier, I would even go as far as dealing with the database or whatever it would take to improve it.

But that's not what happened. And it was not a matter of you guys taking your time to review the PR. You simply decided to ignore it completely.

I have developed some familiarity with the codebase, but I don't think I'll be contributing to Signal anymore. You guys should really improve your relationship with the Open Source Community. A software isn't a good OSS simply because its source code is available/licensed online.

**Comment by moxie0** [comment]
@gabrielsimoes To "improve" this PR, you would need to modify the service protocol, publish new service libs, then make the corresponding changes on iOS and Desktop, then coordinate a release with an incrementally staged rollout of receive support and send support between all three. That's on top of all the individual changes to your code style, logic, etc. No amount of feedback from us is going to make that happen here.

Please look at the number of open issues here and feature requests on the forums, then the number of maintainers here (1 full time android person). The purpose of GH is to create an environment that we, the developers who are ultimately responsible for this project, find useful for improving Signal. What we find useful is what we've detailed in the contributing guidelines. In particular, for code contributions, what we find useful are very small, well tested PRs, where most of the work went into figuring out which 3 lines needed to change rather than writing the code. I'm impressed that you delved so deeply into the code in order to implement something you care about, but unfortunately an 800 line PR that introduces a major feature which ultimately needs to be a protocol change and coordinated release across three platforms as your first contribution is not useful to us when it comes to shipping a production piece of software.

**Pull request closed without merging**
