### PR TITLE
Fixes #12119: Remove redundant exit animation from v21/themes

### LINKED ISSUE #12119: Flicker when minimizing conversation settings
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
When you minimize a conversation's settings' page, it flickers before getting completely minimized.

### Steps to reproduce
- Open a conversation
- Close and open the conversation's settings
- Observe the flicker

**Actual result:** Screen flickers
**Expected result:** Flickers are elided.

### Screenshots
[](https://user-images.githubusercontent.com/34171942/161401100-8b2cd3d0-a791-443f-a39c-bde661c6e9a4.mp4)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

### PR DESCRIPTION
**Pull request by clauz9**
### Contributor checklist

- [x] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [x] I have tested my contribution on these devices:
 * Huawei L29, Android 8
- [x] My contribution is fully baked and ready to be merged as is
- [x] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### Description

the Finish() method that is overridden in [ConversationSettingsActivity](https://github.com/signalapp/Signal-Android/blob/master/app/src/main/java/org/thoughtcrime/securesms/components/settings/conversation/ConversationSettingsActivity.kt) uses [overridePendingTransition](https://github.com/signalapp/Signal-Android/blob/d11e8ec04b0b0a66649775e0eb84ce6e51abbb00/app/src/main/java/org/thoughtcrime/securesms/components/settings/conversation/ConversationSettingsActivity.kt#L34) to trigger an exit animation, 
therefore having the same exit animation defined in the [v21/themes.xml](https://github.com/signalapp/Signal-Android/blob/d11e8ec04b0b0a66649775e0eb84ce6e51abbb00/app/src/main/res/values-v21/themes.xml#L79) file creates the visual glitch reported in #12119

fixes #12119

### CODE REVIEW

**Comment by Xashyar** [comment]
Thanks @clauz9,
For investigating and fixing the issue. 🙏

**Comment by Xashyar** [comment]
Thanks @clauz9,
For investigating and fixing the issue. 

I could no longer reproduce it on Signal (Canary). 🙏

**Comment by greyson-signal** [comment]
(Note: This change will be in 5.36 - thanks!)

**Comment by clauz9** [comment]
this has been merged

**Pull request closed without merging**
